---
title: "Updated Analysis of Carbon DATA"
author: "Jenn_McHenry"
date: "3/02/2021"
output: html_document
---

## R Markdown

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(lubridate)
library(plyr)
library(raster)
library(sp)
library(ggplot2)
library(forcats)
library(ggthemes)


theme_Publication <- function(base_size=14, base_family="helvetica") {
      library(grid)
      library(ggthemes)
      (theme_foundation(base_size=base_size, base_family=base_family)
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "bottom",
               legend.direction = "horizontal",
               legend.key.size= unit(0.2, "cm"),
               legend.margin = unit(0, "cm"),
               legend.title = element_text(face="italic"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
          ))
      
}

scale_fill_Publication <- function(...){
      library(scales)
      discrete_scale("fill","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

scale_colour_Publication <- function(...){
      library(scales)
      discrete_scale("colour","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}
```

#Loading in the seagrass survey data 
```{r}

#Seagrass Data
seagrass_surveys=read.csv("data_output/Seagrass_Species_Cover_QAQC_with_Environmental_Factors.csv")
head(seagrass_surveys)
summary(seagrass_surveys)
names(seagrass_surveys)

seagrass_surveys=seagrass_surveys%>%
  mutate(Seagrass_Spp=(Thalassia.testudinum+Syringodium.filiforme+Halodule.wrightii+Halophila.decipens+Halophila.engelmanni+Ruppia.maritima),Algal_Spp=(Acanthophora.spicifera+Caulerpa.verticillata+Halimeda.incrassata+Penicillus.capitatus+Sargassum+Udotea.flabellum))


#Seagrass Clippings
seagrass_clippings=read.csv("data/Carbon/Seagrass_Clippings_Data_version_11_23_2020.csv")

seagrass_clippings=seagrass_clippings%>%
  mutate(Dry_Weight_Corrected=Dry.Weight..g.- Boat.Weight..g.)

names(seagrass_clippings)

seagrass_clippings=seagrass_clippings[c(2:7,17,16)]

colnames(seagrass_clippings)<-c("Site","Quadrat","Species","Common.Name","Species_Type","Biomass_Type","Sample_gDW","Notes")

seagrass_clippings=seagrass_clippings%>%
  dplyr::filter(Species_Type=="SAV" | Species_Type=="Algae")%>%
  filter(Biomass_Type=="AGB" | Biomass_Type=="ABG")%>%
  filter(Sample_gDW>0)
summary(seagrass_clippings)
names(seagrass_clippings)

seagrass_clippings_Quadrat=seagrass_clippings%>%
  dplyr::group_by(Site,Quadrat,Species)%>%
  dplyr::summarize(Biomass_gDW=mean(Sample_gDW))%>%
  dplyr::filter(Species!="epiphytic_algae")%>%
  tidyr::spread(key = Species,value = Biomass_gDW,fill = 0)%>%
  mutate(Macro_Algae_Biomass_gDW=Acanthophora_spicifera+filamentous_red_algae+Halimeda_incrassata+Penicillus_sp +  branched_red_algae + Udotea_flabellum_)%>%
  mutate(Seagrass_Biomass_gDW= Halodule_wrightii + Halophila_decipiens + Halophila_engelmanni + Ruppia_maritima + Syringodium_filiforme + Thalassia_testudinum) 


colnames(seagrass_clippings_Quadrat)<-c("Site","Quadrat","Acanthophora_spicifera_gDW", "Branched_red_algae","Filamentous_algae_gDW", "Halimeda_incrassata_gDW","Halodule_wrightii_gDW",
                                     "Halophila_decipiens_gDW", 
                                     "Halophila_engelmanni_gDW",
                                     "Penicillus_sp_gDW",
                                     "Ruppia_maritima_gDW",
                                     "Syringodium_filiforme_gDW",
                                     "Thalassia_testudinum_gDW",  
                                     "Udotea_flabellum_gDW","Unidentified_Alga_gDW", "Macro_Algae_Biomass_gDW","Seagrass_Biomass_gDW" )

levels(as.factor(seagrass_clippings$Quadrat))


Compation_Ratio=read.csv("data/Carbon/Core_Length_Data_version_10_07_2020.csv")
names(Compation_Ratio)
colnames(Compation_Ratio)<-c("Date","Region","Site","Dive.Name","Original_Quadrat","Insertion_Depth_cm","Core_Length_cm","Compaction_Ratio","Alt_Number","Quadrat","Notes")
dim(Compation_Ratio)
Compation_Ratio=unique(Compation_Ratio)
dim(Compation_Ratio)

Compation_Ratio=Compation_Ratio[c(3,10,6:9)]

Compation_Ratio=Compation_Ratio%>%
  mutate(Compaction_Ratio=round(Compaction_Ratio,2),Core_Length_Corrected_cm=Core_Length_cm*(1/Compaction_Ratio))

levels(Compation_Ratio$Site)

#Sediment Data
Sediment=read.csv("data/Carbon/Sediment_Data_version_03_31_2020.csv")
Sediment=Sediment[c(2:8)]

names(Sediment)<-c("Site","Quadrat","Bagged_Slice_Number","Slice_Number","Analysis","Rhizome_Removed","Slice_Height_cm")

Sediment_QAQC=join(Sediment,Compation_Ratio,by=c("Site","Quadrat"))
Sediment_QAQC=Sediment_QAQC%>%
  dplyr::mutate(Slice_Height_cm=as.numeric(Slice_Height_cm),
                Slice_Height_Corrected_cm=Slice_Height_cm*(1/Compaction_Ratio)) 

Slice_Height_Corrected_cm_Mean=Sediment_QAQC%>%
  dplyr::select(Site,Quadrat,Slice_Height_Corrected_cm)%>%
  dplyr::group_by(Site,Quadrat)%>%
  dplyr::summarize(Mean_Slice_Height_Corrected_cm=mean(Slice_Height_Corrected_cm,na.rm=TRUE))
  # dplyr::mutate(Mean_Slice_Height_Corrected_cm=round(Mean_Slice_Height_Corrected_cm,2))
                


#Code graveyard for calculating the sediment depth
  # dplyr::arrange(desc(Site,Quadrat,Slice_Number))%>%
  # dplyr::group_by(Site,Quadrat)%>%
  # dplyr::mutate(Sediment_Depth_cm=ave(Slice_Height_Corrected_cm, Site,Quadrat, FUN=cumsum)) # a cumulative sum doesn't work because we haven't processed all of the core slices.......Have to do slice number * 2 and then correct for the overall compaction of the core.... It won't be precise. But its best way I can think of right now without haveing someong go back through the bags to check that some slices are larger....
  


#LOI Data
LOI=read.csv("data/Carbon/LOI_Data_version_03_18_2021.csv")
# head(LOI)
names(LOI)

LOI=LOI[c(2:8,11:12,23:35)]
names(LOI)
# head(LOI)

colnames(LOI)=c("Site","Quadrat","Bagged_Slice_Number","Slice_Number","Analysis","Rhizome_Removed","Slice_Height_cm","Shell_gDW","Rhizome_gDW","Frac_OLOI","Frac_ILOI","OLOI","ILOI","Sample_Weight_gDW","Sediment_Weight_gDW","Sample_Density_g_per_ml","Sediment_Density_g_per_ml","Organic_Content_gDW","Inorganic_Content_gDW","Organic_Content_Density_g_per_ml","Inorganic_Content_Density_g_per_ml","Percent_Carbon")
levels(LOI$Site)
levels(as.factor(LOI$Quadrat))


LOI=join(Compation_Ratio[c(1:2,4,5,7)],LOI,by=c("Site","Quadrat"))

LOI=join(LOI,Sediment_QAQC[c(1:2,4,13:14)],by=c("Site","Quadrat","Slice_Number"),type="left")
levels(Compation_Ratio$Site)
levels(as.factor(Compation_Ratio$Quadrat))

levels(LOI$Site)
levels(as.factor(LOI$Quadrat))


## GOTTA CHECK THE CALCULATIONS REALLY CLOSELY. I THINK WE NEED TO MULTIPLY PERCENTAGES BY GRAMS BEFORE DIVDING BY THE CORRECTED VOLUME.
# RIGHT NOW I'M CALCULATING DENSITIES AND THEN MULTIPLYING THE PERCENTAGES

LOI_QAQC=LOI%>%
  dplyr::mutate(Slice_Area_cm2=pi*(2.54^2),Slice_Volume_cm3=Slice_Area_cm2*Slice_Height_Corrected_cm)%>%
 dplyr::mutate(Sample_Density_g_per_ml=Sample_Weight_gDW/Slice_Volume_cm3,
         Sediment_Density_g_per_ml=Sediment_Weight_gDW/Slice_Volume_cm3,
         Organic_Content_Density_g_per_ml=Frac_OLOI * Sediment_Density_g_per_ml,
         Inorganic_Content_Density_g_per_ml=Frac_ILOI * Sediment_Density_g_per_ml)%>%
 dplyr::mutate(Frac_Shell=(Shell_gDW)/Sample_Weight_gDW,
         Shell_Density_g_per_ml=Frac_Shell*Sample_Density_g_per_ml, 
         Frac_Rhizome=Rhizome_gDW/Sample_Weight_gDW,
         Rhizome_Density_g_per_ml=Frac_Rhizome*Sample_Density_g_per_ml,
         Rhizome_Density_g_per_ml=ifelse(Rhizome_Removed=="Y",Rhizome_Density_g_per_ml,NA))%>%
  dplyr::select(1:10,26:29,15:16,25,19:20,23:24,31,33)%>%
    dplyr::mutate(Factor=ifelse(Site=="SJBA" | Site=="SJBB" | Site=="SJBC" | Site=="SMARA" | Site=="SMARB" | Site=="SMARC" | Site=="STCHA" |Site=="STCHB" |Site=="STCHC"  ,"Control","Seagrass"),
         Percent_Carbon=(0.4839*OLOI)-0.3648,
         Percent_Carbon=ifelse(Percent_Carbon<0,0.001,Percent_Carbon))



# test<-LOI_QAQC%>%
#     dplyr::select(Factor,Site,Quadrat,Core_Length_cm,Core_Length_Corrected_cm,Slice_Number,Slice_Height_cm,Mean_Slice_Height_Corrected_cm,Compaction_Ratio)%>%
#    dplyr::mutate(diff_slice_height=Slice_Height_cm-2)%>%
#   dplyr::group_by(Factor,Site,Quadrat)%>%
#   dplyr::summarize(original_length=unique(Core_Length_cm),max_slice=max(Slice_Number),added_height=sum(diff_slice_height))%>%
#   mutate(length_calculated=(max_slice*2)+added_height,diff=original_length-length_calculated)
#   
#figurig out the proper slice depth 
Core_Length_QAQC<-LOI_QAQC%>%
  dplyr::select(Factor,Site,Quadrat,Core_Length_cm,Core_Length_Corrected_cm,Slice_Number,Slice_Height_cm,Mean_Slice_Height_Corrected_cm,Compaction_Ratio)%>%
  dplyr::mutate(Sediment_Depth_cm=round(Slice_Height_cm*Slice_Number,2),
         Sediment_Depth_cm_uncompressed=round(Sediment_Depth_cm*(1/Compaction_Ratio)),
         Sediment_Depth_cm_mean_uncompressed=round(Mean_Slice_Height_Corrected_cm,2)*Slice_Number)%>%
  dplyr::group_by(Factor,Site,Quadrat)%>%
  dplyr::summarize(Compaction_Ratio=unique(Compaction_Ratio),
                   original_length=unique(Core_Length_cm),
                   length=unique(round(Core_Length_Corrected_cm,2)),
                   length_calculated_from_slice=max(Sediment_Depth_cm),
                   length_calculated_from_uncompressed_slice=max(Sediment_Depth_cm_uncompressed),
                   length_calculated_from_uncompressed_slice_mean=max(Sediment_Depth_cm_mean_uncompressed))%>%
  dplyr::mutate(diff=length-length_calculated_from_slice,
                   diff_uncompressed=length-length_calculated_from_uncompressed_slice,
                   diff_uncompressed_mean=length-length_calculated_from_uncompressed_slice_mean)

write.csv(Core_Length_QAQC,file="data_output/Core_Lengths_Information_QAQC_03_31_2021.csv")

ggplot(Core_Length_QAQC,aes(length))+geom_histogram()+facet_wrap(~Factor)

LOI_QAQC=LOI_QAQC%>%
   mutate(Sediment_Depth_cm_uncompressed=Slice_Height_cm*(1/Compaction_Ratio)*Slice_Number)%>%
   group_by(Site,Quadrat)%>%
   dplyr::mutate(Sediment_Depth_Group=ifelse(Sediment_Depth_cm_uncompressed<=10, "0-10cm", ifelse(Sediment_Depth_cm_uncompressed>10 & Sediment_Depth_cm_uncompressed<=20,"10-20cm",ifelse(Sediment_Depth_cm_uncompressed>20 & Sediment_Depth_cm_uncompressed<=30,"20-30cm",ifelse(Sediment_Depth_cm_uncompressed>30& Sediment_Depth_cm_uncompressed<=40,"30-40cm","40-50cm")))))
         

write.csv(LOI_QAQC,file="data_output/LOI_Data_version_QAQC_03_31_2020.csv")

#Grain size analysis 
Grainsize=read.csv("data/Carbon/Grainsize_Data_version_03_18_2021.csv")
Grainsize=as.data.frame(Grainsize)
# head(Grainsize)
summary(Grainsize)
names(Grainsize)

Grainsize=Grainsize%>%
  mutate(Qualtiy.Control.Chedck=round(Qualtiy.Control.Chedck,2))%>%
  mutate(Fraction.of.Pebbles=ifelse(Qualtiy.Control.Chedck>1.01,NA,Fraction.of.Pebbles),
         Fraction.of.Gravel=ifelse(Qualtiy.Control.Chedck>1.01,NA,Fraction.of.Gravel),
         Fraction.of.Coarse.Sand=ifelse(Qualtiy.Control.Chedck>1.01,NA,Fraction.of.Coarse.Sand),
         Fraction.of.Medium.Sand=ifelse(Qualtiy.Control.Chedck>1.01,NA,Fraction.of.Medium.Sand),
         Fraction.of.Fine.Sand=ifelse(Qualtiy.Control.Chedck>1.01,NA,Fraction.of.Fine.Sand),
         Fraction.of.Silt.Mud=ifelse(Qualtiy.Control.Chedck>1.01,NA,Fraction.of.Silt.Mud))

Grainsize_QAQC=Grainsize[c(2:11,18:23)]
names(Grainsize_QAQC)
levels(Grainsize_QAQC$Site)
levels(LOI_QAQC$Site)


colnames(Grainsize_QAQC)=c("Site","Quadrat","Bagged_Slice_Number","Slice_Number","Analysis","Rhyzome_Removed","Slice_Height_cm","Sample_Weight_gDW","Rhizome_gDW","Sediment_Weight_gDW","Frac_Pebbles","Frac_Gravel","Frac_Coarse_Sand","Frac_Medium_Sand","Frac_Fine_Sand","Frac_Silt")


Grainsize_QAQC=join(Compation_Ratio[c(1:2,5,7)],Grainsize_QAQC,by=c("Site","Quadrat"))
levels(Grainsize_QAQC$Site)


Grainsize_QAQC=Grainsize_QAQC%>%
  # mutate(Rhizome_Removed=ifelse(Slice_Number==4,"Y","N"))%>%
  dplyr::mutate(Slice_Height_Corrected_cm=Slice_Height_cm*(1/Compaction_Ratio),Slice_Area_cm2=pi*(2.54^2),Slice_Volume_cm3=Slice_Area_cm2*Slice_Height_Corrected_cm, Sediment_Depth_cm_uncompressed=Slice_Height_Corrected_cm*Slice_Number)%>%
  mutate(Sample_Density_g_per_ml=Sample_Weight_gDW/Slice_Volume_cm3,
         Sediment_Density_g_per_ml=Sediment_Weight_gDW/Slice_Volume_cm3,
         Frac_Rhizome=Rhizome_gDW/Sample_Weight_gDW,
         Rhizome_Density_g_per_ml=Frac_Rhizome*Sample_Density_g_per_ml)%>%
    dplyr::mutate(Factor=ifelse(Site=="SJBA" | Site=="SJBB" | Site=="SJBC" | Site=="SMARA" | Site=="SMARB" | Site=="SMARC" | Site=="STCHA" |Site=="STCHB" |Site=="STCHC" ,"Control","Seagrass"))%>%
  mutate(Percent_Shell=Frac_Pebbles*100,Percent_Gravel=Frac_Gravel*100,Percent_Coarse=Frac_Coarse_Sand*100,Percent_Medium=Frac_Medium_Sand*100,Percent_Fine=Frac_Fine_Sand*100,Percent_Silt=Frac_Silt*100)%>%
  dplyr::select(1:8,19:33)

names(Grainsize_QAQC)

# Grainsize_QAQC=Grainsize_QAQC%>%
#   mutate(Percent_Sands=Percent_Coarse+Percent_Medium+Percent_Fine)

write.csv(Grainsize_QAQC,file="data_output/Grainsize_Data_version_QAQC_03_30_2021.csv")


```


#Basic Plots
```{r}
names(LOI_QAQC)

ggplot(Compation_Ratio,aes(x=Compaction_Ratio))+geom_histogram()+xlab("Compaction Ratio") +ylab("Number of Cores")

Compation_Ratio%>%
  ggplot(aes(x=round(Core_Length_Corrected_cm,0)))+geom_histogram()+xlab("Uncompressed Core Length (cm)") +ylab("Number of Cores") 

ggplot(LOI_QAQC,aes(x=round(Sediment_Depth_cm_uncompressed,0)))+geom_histogram(binwidth = 1)+xlab("Sediment Depth (cm)") +ylab("Number of Core Slices")

#Sediments
Grainsize_QAQC_long=Grainsize_QAQC%>%
  dplyr::select(1:2,13:14,16:23)%>%
  gather(key="Grainsize","Percent",7:12)


#grainsizes
ggplot(Grainsize_QAQC_long,aes(x=as.integer(Percent),fill=Factor))+geom_density(position = "dodge",alpha=0.5) + xlab("Percent Grainsize per Slice") + ylab("Frequency") + facet_wrap(~Grainsize,scale="free_y")

```



#Looking at slice level data
```{r}
names(LOI_QAQC)

LOI_QAQC_By_Site_Slice=LOI_QAQC%>%
  mutate(Rhizome_Density_g_per_ml=ifelse(is.na(Rhizome_Density_g_per_ml)==TRUE,0,Rhizome_Density_g_per_ml))%>%
  # dplyr::filter(Sediment_Depth_cm_uncompressed<=40)%>%
  dplyr::group_by(Site,Factor,Quadrat,Bagged_Slice_Number,Slice_Number,Slice_Height_Corrected_cm,Sediment_Depth_Group)%>%
  dplyr::summarize(Sediment_Depth_cm=unique(round(Sediment_Depth_cm_uncompressed,0)),OLOI=mean(OLOI,na.rm=TRUE),ILOI=mean(ILOI,na.rm=TRUE),Organic_Content_Density_g_per_ml=mean(Organic_Content_Density_g_per_ml,na.rm=TRUE),Inorganic_Content_Density_g_per_ml=mean(Inorganic_Content_Density_g_per_ml,na.rm=TRUE),Percent_Carbon=mean(Percent_Carbon,na.rm=TRUE),Rhizome_Density_g_per_ml=mean(Rhizome_Density_g_per_ml,na.rm=TRUE),Shell_Density_g_per_ml=mean(Shell_Density_g_per_ml,na.rm=TRUE),Sediment_Density_g_per_ml=mean(Sediment_Density_g_per_ml,na.rm=TRUE),Sample_Density_g_per_ml=mean(Sample_Density_g_per_ml,na.rm=TRUE))%>% #calling sediment depth as is to avoid renaming below. But not its the uncompressed versions
  ungroup()%>%
  filter(is.na(OLOI)==FALSE)%>%
  dplyr::mutate(Organic_Carbon_Density_g_per_ml=(Percent_Carbon/100) * Sediment_Density_g_per_ml,
         Inorganic_Carbon_Density_g_per_ml=(Inorganic_Content_Density_g_per_ml* 0.12),
         Total_Carbon_Density_g_per_ml=Organic_Carbon_Density_g_per_ml+Inorganic_Carbon_Density_g_per_ml)%>%
    mutate(Sediment_Depth_Factor=ifelse(Sediment_Depth_cm<=20,"shallow","deep"))%>%
  mutate(Sediment_Depth_Factor=factor(Sediment_Depth_Factor,levels=c("shallow","deep")))


LOI_QAQC_By_Site_Slice%>%
  dplyr::group_by(Sediment_Depth_Group,Factor)%>%
  dplyr::summarise(mean=mean(OLOI),n=n())

ggplot(LOI_QAQC_By_Site_Slice,aes(x=(Sediment_Depth_cm)))+geom_histogram(binwidth = 1)+xlab("Sediment Depth (cm)") +ylab("Frequency")

#Rhizome 
p1=LOI_QAQC_By_Site_Slice%>%
  dplyr::group_by(Factor,Sediment_Depth_Group)%>%
  dplyr::summarize(mean=mean(Rhizome_Density_g_per_ml,na.rm=TRUE),SD=sd(Rhizome_Density_g_per_ml),N=n(),SE=SD/sqrt(N))%>%
    ggplot(aes(y=(mean),x=fct_rev(Sediment_Depth_Group),color=Factor,fill=Factor))+ geom_point() + ylab("Rhizome Density (g/cm3) of Slice") + xlab("Sediment Depth (cm)") +geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE), width=.2) +coord_flip()+ ggtitle("A") +theme_Publication() +scale_colour_Publication() +theme(legend.position="none")


#Organic Carbon Density
p2=LOI_QAQC_By_Site_Slice%>%
  dplyr::group_by(Factor,Sediment_Depth_Group)%>%
  dplyr::summarize(mean=mean(Organic_Carbon_Density_g_per_ml,na.rm=TRUE),SD=sd(Organic_Carbon_Density_g_per_ml,na.rm=TRUE),N=n(),SE=SD/sqrt(N))%>%
    ggplot(aes(y=(mean),x=fct_rev(Sediment_Depth_Group),color=Factor,fill=Factor))+ geom_point() + ylab("OC Density (g/cm3) of Slice") + xlab("Sediment Depth (cm)") +geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE))+coord_flip()+ggtitle("B") +theme_Publication() +scale_colour_Publication() +theme(legend.position="none")



#Inorganic Carbon Density
p3=LOI_QAQC_By_Site_Slice%>%
  dplyr::group_by(Factor,Sediment_Depth_Group)%>%
  dplyr::summarize(mean=mean(Inorganic_Carbon_Density_g_per_ml,na.rm=TRUE),SD=sd(Inorganic_Carbon_Density_g_per_ml,na.rm=TRUE),N=n(),SE=SD/sqrt(N))%>%
    ggplot(aes(y=(mean),x=fct_rev(Sediment_Depth_Group),color=Factor,fill=Factor))+ geom_point() + ylab("IOC Density (g/cm3) of Slice") + xlab("Sediment Depth (cm)") +geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE)) +coord_flip()+ggtitle("C") +theme_Publication() +scale_colour_Publication() +theme(legend.position="none")


plot_grid(p1, p2,p3,nrow = 1)


## BY DEPTH
# Rhizome (g/ml) 
p4=LOI_QAQC_By_Site_Slice%>%
  dplyr::mutate(Sediment_Depth_cm=as.factor(as.integer(Sediment_Depth_cm)))%>%
  dplyr::group_by(Factor,Site,Quadrat,Sediment_Depth_cm)%>%
  dplyr::summarize(mean=mean(Rhizome_Density_g_per_ml,na.rm=TRUE))%>%
  mutate(Sediment_Depth_cm=as.integer(Sediment_Depth_cm))%>%
    ggplot(aes(y=(mean),x=-Sediment_Depth_cm,color=Factor,fill=Factor))+geom_point() + geom_smooth(method="lm",) + ylab("Rhizome Density (g/cm3) of Slice") + xlab("Sediment Depth (cm)")+ coord_flip()+ggtitle("A") +theme_Publication() +scale_colour_Publication() +theme(legend.position="none")




#testing for relationship with slice depth 
rhiz_depth_lm=lm(Rhizome_Density_g_per_ml ~ Sediment_Depth_cm *Factor, data=LOI_QAQC_By_Site_Slice)
summary(rhiz_depth_lm)



# Organic Carbon Density
p5=LOI_QAQC_By_Site_Slice%>%
  dplyr::mutate(Sediment_Depth_cm=as.factor(as.integer(Sediment_Depth_cm)))%>%
  dplyr::group_by(Factor,Site,Quadrat,Sediment_Depth_cm,Sediment_Depth_Factor)%>%
  dplyr::summarize(mean=mean(Organic_Carbon_Density_g_per_ml,na.rm=TRUE))%>%
  mutate(Sediment_Depth_cm=as.integer(Sediment_Depth_cm))%>%
              ggplot(aes(y=(mean),x=-Sediment_Depth_cm,color=Factor,fill=Factor))+geom_point() + geom_smooth(method="lm",) + ylab("OC Density (g/cm3)") + xlab("Sediment Depth (cm)") + ggtitle("OC Density by Sediment Depth ")+coord_flip()+ggtitle("B") +theme_Publication() +scale_colour_Publication()+theme(legend.position="none")




OCD_shallow_lm=lm(Organic_Carbon_Density_g_per_ml ~ Sediment_Depth_cm + Factor, data=LOI_QAQC_By_Site_Slice[LOI_QAQC_By_Site_Slice$Sediment_Depth_Factor=="shallow",])
summary(OCD_shallow_lm)

OCD_deep_lm=lm(Organic_Carbon_Density_g_per_ml ~ Sediment_Depth_cm + Factor, data=LOI_QAQC_By_Site_Slice[LOI_QAQC_By_Site_Slice$Sediment_Depth_Factor=="deep",])
summary(OCD_deep_lm)


# Inorganic Carbon Density
p6=LOI_QAQC_By_Site_Slice%>%
  dplyr::mutate(Sediment_Depth_cm=as.factor(as.integer(Sediment_Depth_cm)))%>%
  dplyr::group_by(Factor,Site,Quadrat,Sediment_Depth_cm,Sediment_Depth_Factor)%>%
  dplyr::summarize(mean=mean(Inorganic_Carbon_Density_g_per_ml,na.rm=TRUE))%>%
  mutate(Sediment_Depth_cm=as.integer(Sediment_Depth_cm))%>%
              ggplot(aes(y=(mean),x=-Sediment_Depth_cm,color=Factor,fill=Factor))+geom_point() + geom_smooth(method="lm",) + ylab("IOC Density (g/cm3)") + xlab("Sediment Depth (cm)") + ggtitle("IOC Density by Sediment Depth ")+coord_flip()+ggtitle("C") +theme_Publication() +scale_colour_Publication() +theme(legend.position="none")



ICD_shallow_lm=lm(Inorganic_Carbon_Density_g_per_ml ~ Sediment_Depth_cm + Factor, data=LOI_QAQC_By_Site_Slice[LOI_QAQC_By_Site_Slice$Sediment_Depth_Factor=="shallow",])
summary(ICD_shallow_lm)

ICD_deep_lm=lm(Inorganic_Carbon_Density_g_per_ml ~ Sediment_Depth_cm * Factor, data=LOI_QAQC_By_Site_Slice[LOI_QAQC_By_Site_Slice$Sediment_Depth_Factor=="deep",])
summary(ICD_deep_lm)


plot_grid(p4, p5,p6,nrow = 1)

p7=p5+facet_wrap(~Sediment_Depth_Factor, scale="free_y")+theme(legend.position="none")+ggtitle("A")

p8=p6+facet_wrap(~Sediment_Depth_Factor, scale="free_y") +theme(legend.position="bottom")+ggtitle("B")

OCD_all_lm=lm(Organic_Carbon_Density_g_per_ml ~ Factor +Sediment_Depth_Factor, data=LOI_QAQC_By_Site_Slice)
summary(OCD_all_lm)


ICD_all_lm=lm(Inorganic_Carbon_Density_g_per_ml ~ Factor*Sediment_Depth_Factor, data=LOI_QAQC_By_Site_Slice)
summary(ICD_all_lm)

plot_grid(p7, p8,ncol = 1)


#Rhizome 
p9=LOI_QAQC_By_Site_Slice%>%
  dplyr::group_by(Factor,Sediment_Depth_Factor)%>%
  dplyr::summarize(mean=mean(Rhizome_Density_g_per_ml,na.rm=TRUE),SD=sd(Rhizome_Density_g_per_ml),N=n(),SE=SD/sqrt(N))%>%
    ggplot(aes(y=(mean),x=fct_rev(Sediment_Depth_Factor),color=Factor,fill=Factor))+ geom_point() + ylab("Rhizome Density (g/cm3) of Slice") + xlab("Sediment Depth Bin") +geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE), width=.2) +coord_flip()+ ggtitle("A") +theme_Publication() +scale_colour_Publication() +theme(legend.position="none")

#Organic Carbon Density
p10=LOI_QAQC_By_Site_Slice%>%
  dplyr::group_by(Factor,Sediment_Depth_Factor)%>%
  dplyr::summarize(mean=mean(Organic_Carbon_Density_g_per_ml,na.rm=TRUE),SD=sd(Organic_Carbon_Density_g_per_ml,na.rm=TRUE),N=n(),SE=SD/sqrt(N))%>%
    ggplot(aes(y=(mean),x=fct_rev(Sediment_Depth_Factor),color=Factor,fill=Factor))+ geom_point() + ylab("OC Density (g/cm3) of Slice") + xlab("Sediment Depth Bin") +geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE))+coord_flip()+ggtitle("B") +theme_Publication() +scale_colour_Publication() +theme(legend.position="none")



#Inorganic Carbon Density
p11=LOI_QAQC_By_Site_Slice%>%
  dplyr::group_by(Factor,Sediment_Depth_Factor)%>%
  dplyr::summarize(mean=mean(Inorganic_Carbon_Density_g_per_ml,na.rm=TRUE),SD=sd(Inorganic_Carbon_Density_g_per_ml,na.rm=TRUE),N=n(),SE=SD/sqrt(N))%>%
    ggplot(aes(y=(mean),x=fct_rev(Sediment_Depth_Factor),color=Factor,fill=Factor))+ geom_point() + ylab("IOC Density (g/cm3) of Slice") + xlab("Sediment Depth Bin") +geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE)) +coord_flip()+ggtitle("C") +theme_Publication() +scale_colour_Publication() +theme(legend.position="none")


plot_grid(p9, p10,p11,nrow = 1)


```

#Combinging analytical datasets to Quadrat level 
```{r}

#LOI ESITMATES #########################################################3
LOI_QAQC_Quadrat_Level_By_DepthBin=LOI_QAQC_By_Site_Slice%>%
  mutate(Organic_accum_per_cm=Organic_Content_Density_g_per_ml*Slice_Height_Corrected_cm,
  Inorganic_accum_per_cm=Inorganic_Content_Density_g_per_ml*Slice_Height_Corrected_cm,
  Shell_accum_per_cm=Shell_Density_g_per_ml*Slice_Height_Corrected_cm,
  Rhizome_accum_per_cm=Rhizome_Density_g_per_ml*Slice_Height_Corrected_cm,
  Organic_Carbon_accum_per_cm=Organic_Carbon_Density_g_per_ml*Slice_Height_Corrected_cm,
  Inorganic_Carbon_accum_per_cm=Inorganic_Carbon_Density_g_per_ml*Slice_Height_Corrected_cm)%>%
  dplyr::group_by(Site,Factor,Sediment_Depth_Factor,Quadrat)%>% #AVERAGING WITHIN A QUADRAT
  dplyr::summarize(OLOI=mean(OLOI,na.rm=TRUE),
                   ILOI=mean(ILOI,na.rm=TRUE),
                   Carbon=mean(Percent_Carbon,na.rm=TRUE),
                   Organic_accum_per_cm=mean(Organic_accum_per_cm,na.rm=TRUE),
                   Inorganic_accum_per_cm=mean(Inorganic_accum_per_cm,na.rm=TRUE),
                   Shell_accum_per_cm=mean(Shell_accum_per_cm,na.rm=TRUE),
                   Rhizome_accum_per_cm=mean(Rhizome_accum_per_cm,na.rm=TRUE),
                   Organic_Carbon_accum_per_cm=mean(Organic_Carbon_accum_per_cm,na.rm=TRUE),
                   Inorganic_Carbon_accum_per_cm=mean(Inorganic_Carbon_accum_per_cm,na.rm=TRUE))%>% # Converting the estiamtes to Value within a squre meter area up to 50cm sediment depth. (and 10 cm depth for rhizomes)
  dplyr::mutate(Stock_Scaling_Factor=ifelse(Sediment_Depth_Factor=="shallow",20,35),
                OM_g_per_sqm=Organic_accum_per_cm*(1/0.0001),
         IOM_accum_per_sqm=Inorganic_accum_per_cm*(1/0.0001),
         Shell_accum_per_sqm=Shell_accum_per_cm*(1/0.0001),
         Rhizome_accum_per_sqm=Rhizome_accum_per_cm*(1/0.0001),
         OC_Stock_accum_per_sqm=Organic_Carbon_accum_per_cm*(1/0.0001),
         IOC_Stock_accum_per_sqm=Inorganic_Carbon_accum_per_cm*(1/0.0001),
         Total_C_accum_g_per_sqm=OC_Stock_accum_per_sqm+IOC_Stock_accum_per_sqm)%>%
  dplyr::ungroup()%>%
  dplyr::select(1:6,15:21)

Reference_Combo=LOI_QAQC_Quadrat_Level_By_DepthBin[c(1:2,4)]
Reference_Combo=unique(Reference_Combo)


#SEAGRASS ESITMATES #########################################################3

seagrass_surveys_By_Quadrat=join(Reference_Combo,seagrass_surveys[c(1:8,15:22,32:36,76:77)],by=c("Site","Quadrat"),type="left",match="first")
  
  
seagrass_surveys_By_Quadrat=seagrass_surveys_By_Quadrat%>%
  mutate(Total_Seagrass_Cover=(Seagrass_Spp/100)*(SAV_Cover/100)*100,
         Total_Algae_Cover=(Algal_Spp/100)*(SAV_Cover/100)*100)



seagrass_survey_AND_Clippings_By_Quadrat=join(seagrass_surveys_By_Quadrat,seagrass_clippings_Quadrat[c(1:2,17,16,13,12,7)],by=c("Site","Quadrat"))

Environmental_Factors_Sites=seagrass_surveys%>%
  dplyr::select(Site,Latitude,Longitude,Temperature.Mean,Depth_m,Secchi_m,Current.Velocity.Max,Salinity.Min,Chlorophyll.Mean,Nitrate.Mean,Phosphate.Mean,Light.bottom.Min,Par.Mean,Dist_To_River,Dist_To_Shore)%>%
  group_by(Site)%>%
  dplyr::summarize(Latitude=mean(Latitude,na.rm=TRUE),Longitude=mean(Longitude,na.rm=TRUE),Depth_m=mean(Depth_m,na.rm=TRUE),Secchi_m=mean(Secchi_m,na.rm=TRUE),Temperature.Mean=mean(Temperature.Mean,na.rm=TRUE),Current.Velocity.Max=mean(Current.Velocity.Max,na.rm=TRUE),Salinity.Min=mean(Salinity.Min,na.rm=TRUE),Chlorophyll.Mean=mean(Chlorophyll.Mean,na.rm=TRUE),Nitrate.Mean=mean(Nitrate.Mean,na.rm=TRUE),Phosphate.Mean=mean(Phosphate.Mean,na.rm=TRUE),Light.bottom.Min=mean(Light.bottom.Min,na.rm=TRUE),Par.Mean=mean(Par.Mean,na.rm=TRUE),Dist_To_River=mean(Dist_To_River,na.rm=TRUE),Dist_To_Shore=mean(Dist_To_Shore,na.rm=TRUE))%>%
  ungroup()


seagrass_survey_AND_Clippings_By_Quadrat=join(seagrass_survey_AND_Clippings_By_Quadrat,Environmental_Factors_Sites,by="Site",type="left")



Seagrass_Data_Quadrat_Level=seagrass_survey_AND_Clippings_By_Quadrat%>%
  mutate(Seagrass_Biomass_g_per_sqm=Seagrass_Biomass_gDW/0.0625,
         Macro_Algae_Biomass_g_per_sqm=Macro_Algae_Biomass_gDW/0.0625,
         Thalassia_testudinum_g_per_sqm=Thalassia_testudinum_gDW/0.0625,
         Syringodium_filiforme_g_per_sqm=Syringodium_filiforme_gDW/0.0625,
         Halodule_wrightii_g_per_sqm=Halodule_wrightii_gDW/0.0625)%>%
  dplyr::select(1:3,7:26,46:50,32:45)

write.csv(Seagrass_Data_Quadrat_Level,"data_output/Seagrass_Data_QAQC_Quadrat_Level_03_31_2021.csv")


LOI_QAQC_Quadrat_Level_By_DepthBin=plyr::join(LOI_QAQC_Quadrat_Level_By_DepthBin,Seagrass_Data_Quadrat_Level[c(1:2,4)],by=c("Site","Quadrat"),type="left")


#GRAINSIZE ESITMATES #########################################################3

Grainsize_QAQC_Quadrat_Level_By_DepthBin=Grainsize_QAQC%>%
 mutate(Sediment_Depth_Factor=ifelse(Sediment_Depth_cm_uncompressed<=20,"shallow","deep"))%>%
  mutate(Sediment_Depth_Factor=factor(Sediment_Depth_Factor,levels=c("shallow","deep")))%>%
  group_by(Site,Quadrat,Sediment_Depth_Factor)%>%
  dplyr::summarize(Percent_Shell=mean(Percent_Shell,na.rm=TRUE),Percent_Gravel=mean(Percent_Gravel,na.rm=TRUE),Percent_Coarse=mean(Percent_Coarse,na.rm=TRUE),Percent_Medium=mean(Percent_Medium,na.rm=TRUE),Percent_Fine=mean(Percent_Fine,na.rm=TRUE),Percent_Silt=mean(Percent_Silt,na.rm=TRUE))%>%
  ungroup()

# Grainsize_QAQC_Quadrat_Level_By_DepthBin[is.na(Grainsize_QAQC_Quadrat_Level_By_DepthBin)] <- NA


```

#Getting Site Level Data 
```{r}
#GOING TO SITE LEVEL BY DEPTH BIN
LOI_QAQC_Site_Level_By_DepthBin=LOI_QAQC_Quadrat_Level_By_DepthBin%>%
  dplyr::group_by(Site,Factor,Sediment_Depth_Factor)%>%
  dplyr::summarize(OLOI=mean(OLOI,na.rm=TRUE),
                   ILOI=mean(ILOI,na.rm=TRUE),
                   Rhizome_accum_per_sqm=mean(Rhizome_accum_per_sqm,na.rm=TRUE),
                   Shell_accum_per_sqm=mean(Shell_accum_per_sqm,na.rm=TRUE),
                   OC_Stock_accum_per_sqm=mean(OC_Stock_accum_per_sqm,na.rm=TRUE),
                   IOC_Stock_accum_per_sqm=mean(IOC_Stock_accum_per_sqm,na.rm=TRUE),
                   Total_C_accum_g_per_sqm=mean(Total_C_accum_g_per_sqm,na.rm=TRUE))%>%
      ungroup()



Seagrass_Data_Site_Level=Seagrass_Data_Quadrat_Level%>%
  dplyr::group_by(Region,Site,Factor,Seagrass_Landscape)%>%
  dplyr::summarize_all(mean,na.rm=TRUE)



Grainsize_QAQC_Site_Level_By_DepthBin=Grainsize_QAQC_Quadrat_Level_By_DepthBin%>%
  group_by(Site,Sediment_Depth_Factor)%>%
  dplyr::summarize(Percent_Shell=mean(Percent_Shell,na.rm=TRUE),Percent_Gravel=mean(Percent_Gravel,na.rm=TRUE),Percent_Coarse=mean(Percent_Coarse,na.rm=TRUE),Percent_Medium=mean(Percent_Medium,na.rm=TRUE),Percent_Fine=mean(Percent_Fine,na.rm=TRUE),Percent_Silt=mean(Percent_Silt,na.rm=TRUE))%>%
  ungroup()
names(Grainsize_QAQC_Site_Level_By_DepthBin)

# Grainsize_QAQC_Site_Level_By_DepthBin[is.na(Grainsize_QAQC_Site_Level_By_DepthBin)] <- NA


```


#MAKING THE BLUE CARBON DATASETS
```{r}

#Quadrat Level
BlueCarbon_QAQC_Quadrat_Level_By_DepthBin=plyr::join(LOI_QAQC_Quadrat_Level_By_DepthBin,Seagrass_Data_Quadrat_Level,by=c("Region","Site","Quadrat","Factor"),match="all",type="inner")


BlueCarbon_QAQC_Quadrat_Level_By_DepthBin=plyr::join(BlueCarbon_QAQC_Quadrat_Level_By_DepthBin,Grainsize_QAQC_Quadrat_Level_By_DepthBin,by=c("Site","Quadrat","Sediment_Depth_Factor"),match="all",type="left")


#There are NAs because some of the cores don't have a deep grainsize slice.

New_Dist_To_River<-read.csv("arc_output/New_Dist_To_River_Calculation.csv")
Meadow_Structure<-read.csv("data/Carbon/Seagrass_Meadow_Type_Data_QAQC_2019.csv")

BlueCarbon_QAQC_Quadrat_Level_By_DepthBin=join(BlueCarbon_QAQC_Quadrat_Level_By_DepthBin,Meadow_Structure[c(4:5)],by=c("Site"),match="all",type="inner")

BlueCarbon_QAQC_Quadrat_Level_By_DepthBin=join(BlueCarbon_QAQC_Quadrat_Level_By_DepthBin,New_Dist_To_River[c(2,5)],by=c("Site"),match="all",type="inner")

BlueCarbon_QAQC_Quadrat_Level_By_DepthBin$Dist_To_River<-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin$Dist_To_River_km


names(BlueCarbon_QAQC_Quadrat_Level_By_DepthBin)

BlueCarbon_QAQC_Quadrat_Level_By_DepthBin=BlueCarbon_QAQC_Quadrat_Level_By_DepthBin[c(1,3:20,22:59)]%>%
  mutate(Cover_Level=ifelse(Total_Seagrass_Cover>=50,"high",ifelse(Total_Seagrass_Cover<50 & Total_Seagrass_Cover>=5,"low",ifelse(Total_Seagrass_Cover<5,"none", NA))))%>%
  mutate(TH_PA=ifelse(Thalassia.testudinum>0,1,0),SY_PA=ifelse(Syringodium.filiforme>0,1,0),HA_PA=ifelse(Halodule.wrightii>0,1,0),TH_PA=as.factor(TH_PA),SY_PA=as.factor(SY_PA),HA_PA=as.factor(HA_PA))# %>%
   #mutate(Factor=ifelse(Cover_Level=="none","Control","Seagrass"))


# test=BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
#     dplyr::group_by(Site,Quadrat)%>%
#     dplyr::summarize(n=n())

names(BlueCarbon_QAQC_Quadrat_Level_By_DepthBin)

  



#Site Level
BlueCarbon_QAQC_Site_Level_By_DepthBin=plyr::join(LOI_QAQC_Site_Level_By_DepthBin,Seagrass_Data_Site_Level,by=c("Site","Factor"),match="all",type="left")
names(BlueCarbon_QAQC_Site_Level_By_DepthBin)


BlueCarbon_QAQC_Site_Level_By_DepthBin=plyr::join(BlueCarbon_QAQC_Site_Level_By_DepthBin,Grainsize_QAQC_Site_Level_By_DepthBin,by=c("Site","Sediment_Depth_Factor"),match="all",type="left")


BlueCarbon_QAQC_Site_Level_By_DepthBin=join(BlueCarbon_QAQC_Site_Level_By_DepthBin,Meadow_Structure[c(4:5)],by=c("Site"),match="all",type="inner")

BlueCarbon_QAQC_Site_Level_By_DepthBin=join(BlueCarbon_QAQC_Site_Level_By_DepthBin,New_Dist_To_River[c(2,5)],by=c("Site"),match="all",type="inner")

BlueCarbon_QAQC_Site_Level_By_DepthBin$Dist_To_River<-BlueCarbon_QAQC_Site_Level_By_DepthBin$Dist_To_River_km


names(BlueCarbon_QAQC_Site_Level_By_DepthBin)

BlueCarbon_QAQC_Site_Level_By_DepthBin=BlueCarbon_QAQC_Site_Level_By_DepthBin[c(1:11,13:57)]%>%
  mutate(Cover_Level=ifelse(Total_Seagrass_Cover>=50,"high",ifelse(Total_Seagrass_Cover<50 & Total_Seagrass_Cover>=5,"low",ifelse(Total_Seagrass_Cover<5,"none", NA))))%>%
  mutate(TH_PA=ifelse(Thalassia.testudinum>0,1,0),SY_PA=ifelse(Syringodium.filiforme>0,1,0),HA_PA=ifelse(Halodule.wrightii>0,1,0),TH_PA=as.factor(TH_PA),SY_PA=as.factor(SY_PA),HA_PA=as.factor(HA_PA)) %>%
   mutate(Factor=ifelse(Cover_Level=="none","Control","Seagrass"))


# test=BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
#     dplyr::group_by(Site,Quadrat)%>%
#     dplyr::summarize(n=n())

summary(BlueCarbon_QAQC_Site_Level_By_DepthBin)

BlueCarbon_QAQC_Quadrat_Level_By_DepthBin=plyr::join(BlueCarbon_QAQC_Quadrat_Level_By_DepthBin,BlueCarbon_QAQC_Site_Level_By_DepthBin[c(1:2)],by="Site")



write.csv(BlueCarbon_QAQC_Quadrat_Level_By_DepthBin,file="data_output/BlueCarbon_QAQC_Quadrat_Level_By_DepthBin.csv")

  
write.csv(BlueCarbon_QAQC_Site_Level_By_DepthBin,file="data_output/BlueCarbon_QAQC_Site_Level_By_DepthBin.csv")


save.image(file="C:/Users/jennm/Dropbox/GITHUB/Disseratation/Saved_RData/Blue_Carbon_Datasets.RData")

```



# Quad Level Plots
```{r}
#LOI PLOTS #########################################################3
p1_QL_shallow<-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
  dplyr::filter(Sediment_Depth_Factor=="shallow")%>%
  dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_accum_per_sqm,OC_Stock_accum_per_sqm,IOC_Stock_accum_per_sqm)%>%
  mutate(Factor=factor(Factor,labels=c("Bare","Seagrass")))%>%
  dplyr::group_by(Region,Factor)%>%
  ggplot(aes(y=Rhizome_accum_per_sqm,x=Factor,fill=Factor))+geom_boxplot()+ ylab("Rhizome  (g/sqm/cm)") + xlab("Survey Strata") +
  ggtitle("A") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none")+facet_wrap(~Region)

p1_QL_deep<-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
  dplyr::filter(Sediment_Depth_Factor=="deep")%>%
 dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_accum_per_sqm,OC_Stock_accum_per_sqm,IOC_Stock_accum_per_sqm)%>%
  mutate(Factor=factor(Factor,labels=c("Bare","Seagrass")))%>%
  dplyr::group_by(Region,Factor)%>%
  ggplot(aes(y=Rhizome_accum_per_sqm,x=Factor,fill=Factor))+geom_boxplot()+ ylab("Rhizome  (g/sqm/cm)") + xlab("Survey Strata") +
  ggtitle("A") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none")+facet_wrap(~Region)

p2_QL_shallow <-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
  filter(Sediment_Depth_Factor=="shallow")%>%
  dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_accum_per_sqm,OC_Stock_accum_per_sqm,IOC_Stock_accum_per_sqm)%>%
  mutate(Factor=factor(Factor,labels=c("Bare","Seagrass")))%>%
  dplyr::group_by(Region,Factor)%>%
  ggplot(aes(y=OC_Stock_accum_per_sqm,x=Factor,fill=Factor))+geom_boxplot()+ ylab("Organic C (gC/sqm/cm)") + xlab("Survey Strata") +
  ggtitle("B") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none")+facet_wrap(~Region)

p2_QL_deep <-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
  filter(Sediment_Depth_Factor=="deep")%>%
  dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_accum_per_sqm,OC_Stock_accum_per_sqm,IOC_Stock_accum_per_sqm)%>%
  mutate(Factor=factor(Factor,labels=c("Bare","Seagrass")))%>%
  dplyr::group_by(Region,Factor)%>%
  ggplot(aes(y=OC_Stock_accum_per_sqm,x=Factor,fill=Factor))+geom_boxplot()+ ylab("Organic C (gC/sqm/cm)") + xlab("Survey Strata") +
  ggtitle("B") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none")+facet_wrap(~Region)

p3_QL_shallow<-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
    filter(Sediment_Depth_Factor=="shallow")%>%
  dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_accum_per_sqm,OC_Stock_accum_per_sqm,IOC_Stock_accum_per_sqm)%>%
  mutate(Factor=factor(Factor,labels=c("Bare","Seagrass")))%>%
  dplyr::group_by(Region,Factor)%>%
  ggplot(aes(y=IOC_Stock_accum_per_sqm,x=Factor,fill=Factor))+geom_boxplot()+ ylab("Inorganic C (gC/sqm/cm)") + xlab("Survey Strata") +
  ggtitle("C") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none")+facet_wrap(~Region)

p3_QL_deep<-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
    filter(Sediment_Depth_Factor=="deep")%>%
  dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_accum_per_sqm,OC_Stock_accum_per_sqm,IOC_Stock_accum_per_sqm)%>%
  mutate(Factor=factor(Factor,labels=c("Bare","Seagrass")))%>%
  dplyr::group_by(Region,Factor)%>%
  ggplot(aes(y=IOC_Stock_accum_per_sqm,x=Factor,fill=Factor))+geom_boxplot()+ ylab("Inorganic C (gC/sqm/cm)") + xlab("Survey Strata") +
  ggtitle("C") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none")+facet_wrap(~Region)


QL_LOI_grid_shallow=plot_grid(p1_QL_shallow,p2_QL_shallow,p3_QL_shallow,ncol=3,nrow=1)
QL_LOI_grid_deep=plot_grid(p1_QL_deep,p2_QL_deep,p3_QL_deep,ncol=3,nrow=1)


#SEAGRASS PLOTS ##########################################################

p4_QL<-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
  filter(Factor=="Seagrass")%>%
  dplyr::select(Region,SAV_Cover,Total_Seagrass_Cover,Total_Algae_Cover)%>%
  dplyr::group_by(Region)%>%
  tidyr::gather(key = "Cover_Group",value="Percent",-Region)%>%
  mutate(Cover_Group=factor(Cover_Group,levels=c("SAV_Cover","Total_Seagrass_Cover","Total_Algae_Cover"),labels=c("All Vegetation",  "Seagrass",  "Macrophytes")))%>%
  ggplot(aes(y=Percent,x=Cover_Group,fill=Cover_Group))+geom_boxplot()+xlab("Vegetation Type") +ylab("Percent Cover \n(% of Quad)")+ggtitle("A")+theme_Publication()+ scale_fill_Publication() +theme(legend.position="none") +facet_wrap(~Region)


p5_QL<-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
  filter(Factor=="Seagrass")%>%
  dplyr::select(Region,Thalassia.testudinum,Syringodium.filiforme,Halodule.wrightii, Algal_Spp)%>%
  dplyr::group_by(Region)%>%
  tidyr::gather(key = "Species",value="Fraction",-Region)%>%
  mutate(Species=factor(Species,levels=c("Thalassia.testudinum","Syringodium.filiforme","Halodule.wrightii", "Algal_Spp"),labels=c("Turtle","Manatee","Shoal","Macrophytes")))%>%
  ggplot(aes(y=Fraction,x=Species,fill=Species))+geom_boxplot()+xlab("Species") +ylab("Species Composition \n(% of Veg. Cover)")+ggtitle("B")+theme_Publication()+ scale_fill_Publication() +theme(legend.position="none") +facet_wrap(~Region)


p6_QL<-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
  filter(Factor=="Seagrass")%>%
  dplyr::select(Region,Epiphite_Blade_Load,Epiphite_Shoot_Load)%>%
  dplyr::group_by(Region)%>%
  tidyr::gather(key = "Species",value="Fraction",-Region)%>%
  mutate(Species=factor(Species,levels=c("Epiphite_Blade_Load", "Epiphite_Shoot_Load"),labels=c("Epiphite Cover \n(% of Blades Covered)","Epiphyte Density \n(% of Shoots Covered)")))%>%
  ggplot(aes(y=Fraction,x=Species,fill=Species))+geom_boxplot()+xlab("Regiosn") +ylab("Epiphyte Load")+ggtitle("C")+theme_Publication()+ scale_fill_Publication() +theme(legend.position="none") +facet_wrap(~Region)



#GRAINSIZE PLOTS ##########################################################

p7_QL_shallow<-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
    dplyr::filter(Sediment_Depth_Factor=="shallow")%>%
  dplyr::select(Region,Factor,Percent_Gravel,Percent_Coarse,Percent_Medium,Percent_Fine,Percent_Silt)%>%
  tidyr::gather(key = "Grainsizes",value="Percent",3:7)%>%
  dplyr::mutate(Grainsizes=factor(Grainsizes,levels=c("Percent_Gravel","Percent_Coarse","Percent_Medium", "Percent_Fine","Percent_Silt"),labels=c("Gravel","Coarse","Medium","Fine","Silt")))%>%
    dplyr::group_by(Region,Factor,Grainsizes)%>%
  dplyr::summarize(mean=mean(Percent,na.rm=TRUE),SD=sd(Percent),N=n(),SE=SD/sqrt(N))%>%
  ggplot(aes(y=(mean),x=Factor,fill=Grainsizes,group=Factor))+
  # geom_point()+
  geom_bar(stat="identity",position = "fill") +
  ylab("Sediment Composition \n(Fraction of Total Sample)") + xlab("Survey Strata") +
  ggtitle("A") +theme_Publication() +scale_fill_Publication() +theme(legend.position="bottom")+facet_wrap(~Region,ncol=3)

p8_QL_deep<-BlueCarbon_QAQC_Quadrat_Level_By_DepthBin%>%
   dplyr::filter(Sediment_Depth_Factor=="deep")%>%
  dplyr::select(Region,Factor,Percent_Gravel,Percent_Coarse,Percent_Medium,Percent_Fine,Percent_Silt)%>%
  tidyr::gather(key = "Grainsizes",value="Percent",3:7)%>%
  dplyr::mutate(Grainsizes=factor(Grainsizes,levels=c("Percent_Gravel","Percent_Coarse","Percent_Medium", "Percent_Fine","Percent_Silt"),labels=c("Gravel","Coarse","Medium","Fine","Silt")))%>%
    dplyr::group_by(Region,Factor,Grainsizes)%>%
  dplyr::summarize(mean=mean(Percent,na.rm=TRUE),SD=sd(Percent),N=n(),SE=SD/sqrt(N))%>%
  ggplot(aes(y=(mean),x=Factor,fill=Grainsizes,group=Factor))+
  # geom_point()+
  geom_bar(stat="identity",position = "fill") +
  ylab("Sediment Composition \n(Fraction of Total Sample)") + xlab("Survey Strata") +
  ggtitle("B") +theme_Publication() +scale_fill_Publication() +theme(legend.position="bottom")+facet_wrap(~Region,ncol=3)

QL_GRAINSIZES_grid=plot_grid(p7_QL_shallow,p8_QL_deep,ncol=2,nrow=1)

````


#Site Level Plots
```{r}
#LOI PLOTS #########################################################3
p1_SL_shallow<-BlueCarbon_QAQC_Site_Level_By_DepthBin%>%
  dplyr::filter(Sediment_Depth_Factor=="shallow")%>%
  dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_Stock_g_per_sqm,Organic_Carbon_Stock_g_per_sqm,Inorganic_Carbon_Stock_g_per_sqm)%>%
  dplyr::group_by(Region,Factor)%>%
  dplyr::summarize(mean=mean(Rhizome_Stock_g_per_sqm,na.rm=TRUE),SD=sd(Rhizome_Stock_g_per_sqm),N=n(),SE=SD/sqrt(N))%>%
  ggplot(aes(y=(mean),x=Factor,fill=Factor))+ geom_bar(stat="identity",position = "dodge") + ylab("Rhizome Stock (g per sqm)") + xlab("Survey Strata") +
  ggtitle("A") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none")+facet_wrap(~Region)+ geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE,fill=Factor), width=.2)

p1_SL_deep<-BlueCarbon_QAQC_Site_Level_By_DepthBin%>%
  dplyr::filter(Sediment_Depth_Factor=="deep")%>%
  dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_Stock_g_per_sqm,Organic_Carbon_Stock_g_per_sqm,Inorganic_Carbon_Stock_g_per_sqm)%>%
  dplyr::group_by(Region,Factor)%>%
  dplyr::summarize(mean=mean(Rhizome_Stock_g_per_sqm,na.rm=TRUE),SD=sd(Rhizome_Stock_g_per_sqm),N=n(),SE=SD/sqrt(N))%>%
  ggplot(aes(y=(mean),x=Factor,fill=Factor))+ geom_bar(stat="identity",position = "dodge") + ylab("Rhizome Stock (g per sqm)") + xlab("Survey Strata") +
  ggtitle("A") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none")+facet_wrap(~Region)+ geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE,fill=Factor), width=.2)+ylim(0,1500)

p2_SL_shallow <-BlueCarbon_QAQC_Site_Level_By_DepthBin%>%
  filter(Sediment_Depth_Factor=="shallow")%>%
 dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_Stock_g_per_sqm,Organic_Carbon_Stock_g_per_sqm,Inorganic_Carbon_Stock_g_per_sqm)%>%
  dplyr::group_by(Region,Factor)%>%
  dplyr::summarize(mean=mean(Organic_Carbon_Stock_g_per_sqm,na.rm=TRUE),SD=sd(Organic_Carbon_Stock_g_per_sqm),N=n(),SE=SD/sqrt(N))%>%
  ggplot(aes(y=(mean),x=Factor,fill=Factor))+ geom_bar(stat="identity",position=position_dodge()) +facet_wrap(~Region)+ geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE,fill=Factor), width=.2,position=position_dodge(.9)) + ylab("OC Stock (gC per sqm)") + xlab("Survey Strata") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none") +
  ggtitle("B")

p2_SL_deep <-BlueCarbon_QAQC_Site_Level_By_DepthBin%>%
  filter(Sediment_Depth_Factor=="deep")%>%
dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_Stock_g_per_sqm,Organic_Carbon_Stock_g_per_sqm,Inorganic_Carbon_Stock_g_per_sqm)%>%
  dplyr::group_by(Region,Factor)%>%
  dplyr::summarize(mean=mean(Organic_Carbon_Stock_g_per_sqm,na.rm=TRUE),SD=sd(Organic_Carbon_Stock_g_per_sqm),N=n(),SE=SD/sqrt(N))%>%
  ggplot(aes(y=(mean),x=Factor,fill=Factor))+ geom_bar(stat="identity",position=position_dodge()) +facet_wrap(~Region)+ geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE,fill=Factor), width=.2,position=position_dodge(.9)) + ylab("OC Stock (gC per sqm)") + xlab("Survey Strata") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none") +
  ggtitle("B")

p3_SL_shallow<-BlueCarbon_QAQC_Site_Level_By_DepthBin%>%
  filter(Sediment_Depth_Factor=="shallow")%>%
  dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_Stock_g_per_sqm,Organic_Carbon_Stock_g_per_sqm,Inorganic_Carbon_Stock_g_per_sqm)%>%
  dplyr::group_by(Region,Factor)%>%
  dplyr::summarize(mean=mean(Inorganic_Carbon_Stock_g_per_sqm,na.rm=TRUE),SD=sd(Inorganic_Carbon_Stock_g_per_sqm),N=n(),SE=SD/sqrt(N))%>%
  ggplot(aes(y=(mean),x=Factor,fill=Factor))+ geom_bar(stat="identity",position = "dodge") + ylab("IOC Stock (gC per sqm)") + xlab("Sediment Depth Bin") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none")+facet_wrap(~Region)+ geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE,fill=Factor), width=.2,position=position_dodge(.9)) +
  ggtitle("C")

p3_SL_deep<-BlueCarbon_QAQC_Site_Level_By_DepthBin%>%
    filter(Sediment_Depth_Factor=="deep")%>%
  dplyr::select(Region,Factor,Sediment_Depth_Factor,Rhizome_Stock_g_per_sqm,Organic_Carbon_Stock_g_per_sqm,Inorganic_Carbon_Stock_g_per_sqm)%>%
  dplyr::group_by(Region,Factor)%>%
  dplyr::summarize(mean=mean(Inorganic_Carbon_Stock_g_per_sqm,na.rm=TRUE),SD=sd(Inorganic_Carbon_Stock_g_per_sqm),N=n(),SE=SD/sqrt(N))%>%
  ggplot(aes(y=(mean),x=Factor,fill=Factor))+ geom_bar(stat="identity",position = "dodge") + ylab("IOC Stock (gC per sqm)") + xlab("Sediment Depth Bin") +theme_Publication() +scale_fill_Publication() +theme(legend.position="none")+facet_wrap(~Region)+ geom_errorbar(aes(ymin=mean-SE, ymax=mean+SE,fill=Factor), width=.2,position=position_dodge(.9)) +
  ggtitle("C")


QL_LOI_grid_shallow=plot_grid(p1_SL_shallow,p2_SL_shallow,p3_SL_shallow,ncol=3,nrow=1)
QL_LOI_grid_deep=plot_grid(p1_SL_deep,p2_SL_deep,p3_SL_deep,ncol=3,nrow=1)



````


