---
title: "Updated Analysis of Carbon DATA"
author: "Jenn_McHenry"
date: "7/25/2020"
output: html_document
---

## R Markdown

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(lubridate)
library(plyr)
library(raster)
library(sp)
library(ggplot2)
```

#Loading in the seagrass survey data 
```{r}

#Seagrass Data
seagrass_surveys=read.csv("data/Carbon/Seagrass_Species_Cover_QAQC_with_Environmental_Factors.csv")
head(seagrass_surveys)
summary(seagrass_surveys)
names(seagrass_surveys)

seagrass_surveys=seagrass_surveys%>%
  mutate(Seagrass_Spp=(Thalassia.testudinum+Syringodium.filiforme+Halodule.wrightii+Halophila.decipens+Halophila.engelmanni+Ruppia.maritima),Algal_Spp=(Acanthophora.spicifera+Caulerpa.verticillata+Halimeda.incrassata+Penicillus.capitatus+Sargassum+Udotea.flabellum))

Compation_Ratio=read.csv("data/Carbon/Core_Length_Data_version_10_07_2020.csv")
names(Compation_Ratio)
colnames(Compation_Ratio)<-c("Date","Region","Site","Dive.Name","Original_Quadrat","Insertion_Depth_cm","Core_Length_cm","Compaction_Ratio","Alt_Number","Quadrat","Notes")
dim(Compation_Ratio)
Compation_Ratio=unique(Compation_Ratio)
dim(Compation_Ratio)

Compation_Ratio=Compation_Ratio[c(3,10,6:9)]

Compation_Ratio=Compation_Ratio%>%
  mutate(Core_Length_Corrected_cm=Core_Length_cm*(1/Compaction_Ratio))

levels(Compation_Ratio$Site)


#LOI Data
LOI=read.csv("data/Carbon/LOI_Data_version_10_6_2020.csv")
head(LOI)
names(LOI)

LOI_QAQC=LOI[c(2:8,11:12,23:35)]
names(LOI_QAQC)
head(LOI_QAQC)

colnames(LOI_QAQC)=c("Site","Quadrat","Bagged_Slice_Number","Slice_Number","Analysis","Rhizome_Removed","Slice_Height_cm","Shell_gDW","Rhizome_gDW","Frac_OLOI","Frac_ILOI","OLOI","ILOI","Sample_Weight_gDW","Sediment_Weight_gDW","Sample_Density_g_per_ml","Sediment_Density_g_per_ml","Organic_Content_gDW","Inorganic_Content_gDW","Organic_Density_g_per_ml","Inorganic_Density_g_per_ml","Percent_Carbon")
levels(LOI_QAQC$Site)
levels(as.factor(LOI_QAQC$Quadrat))

LOI_QAQC=join(Compation_Ratio[c(1:3,5,7)],LOI_QAQC,by=c("Site","Quadrat"))
levels(Compation_Ratio$Site)
levels(as.factor(Compation_Ratio$Quadrat))

levels(LOI_QAQC$Site)
levels(as.factor(LOI_QAQC$Quadrat))

LOI_QAQC=LOI_QAQC%>%
  dplyr::mutate(Slice_Height_Corrected_cm=(Slice_Height_cm*(1/Compaction_Ratio)),Slice_Volume=pi*(2.54^2)*Slice_Height_Corrected_cm)%>%
 dplyr::mutate(Sample_Density_g_per_ml=Sample_Weight_gDW/Slice_Volume,
         Sediment_Density_g_per_ml=Sediment_Weight_gDW/Slice_Volume,
         Organic_Density_g_per_ml=Frac_OLOI * Sediment_Density_g_per_ml,
         Inorganic_Density_g_per_ml=Frac_ILOI * Sediment_Density_g_per_ml)%>%
 dplyr::mutate(Frac_Shell=Shell_gDW/Sample_Weight_gDW,
         Shell_Density_g_per_ml=Frac_Shell*Sample_Density_g_per_ml,
         Frac_Rhizome=Rhizome_gDW/Sample_Weight_gDW,
         Rhizome_Density_g_per_ml=Frac_Rhizome*Sample_Density_g_per_ml)%>%
  dplyr::select(1:10,26:27,11:25,28:31)%>%
    dplyr::mutate(Factor=ifelse(Site=="SJBA" | Site=="SJBB" | Site=="SJBC" | Site=="SMARA" | Site=="SMARB" | Site=="SMARC" | Site=="STCHA" |Site=="STCHB" |Site=="STCHC"  ,"Control","Seagrass"),
         Percent_Carbon=ifelse(Percent_Carbon<0,0.01,Percent_Carbon))%>%
  dplyr::mutate(Sediment_Depth_cm=Slice_Height_Corrected_cm*Slice_Number,
         Sediment_Depth_Group=ifelse(Sediment_Depth_cm<=10,"0-10cm",ifelse(Sediment_Depth_cm>10 & Sediment_Depth_cm<=20,"10-20cm",ifelse(Sediment_Depth_cm>20 & Sediment_Depth_cm<=30,"20-30cm",ifelse(Sediment_Depth_cm>30 & Sediment_Depth_cm<=40,"30-40cm",ifelse(Sediment_Depth_cm>40 & Sediment_Depth_cm<=50,"40-50cm","below50cm"))))))%>%
  dplyr::select(1:12,17:18,25:27,29,31:34)

write.csv(LOI_QAQC,file="data_output/LOI_Data_version_QAQC_10_6_2020.csv")

#Grain size analysis 
Grainsize=read.csv("data/Carbon/Grainsize_Data_version_10_6_2020.csv")
Grainsize=as.data.frame(Grainsize)
head(Grainsize)
summary(Grainsize)
names(Grainsize)

Grainsize_QAQC=Grainsize[c(2:10,17:22)]
names(Grainsize_QAQC)
levels(Grainsize_QAQC$Site)
levels(LOI_QAQC$Site)


colnames(Grainsize_QAQC)=c("Site","Quadrat","Bagged_Slice_Number","Slice_Number","Analysis","Slice_Height_cm","Sample_Weight_gDW","Rhizome_gDW","Sediment_Weight_gDW","Frac_Pebbles","Frac_Gravel","Frac_Coarse_Sand","Frac_Medium_Sand","Frac_Fine_Sand","Frac_Silt")


Grainsize_QAQC=join(Compation_Ratio[c(1:2,5,7)],Grainsize_QAQC,by=c("Site","Quadrat"))
levels(Grainsize_QAQC$Site)


Grainsize_QAQC=Grainsize_QAQC%>%
  mutate(Rhizome_Removed=ifelse(Slice_Number==4,"Y","N"))%>%
    dplyr::mutate(Slice_Height_Corrected_cm=(Slice_Height_cm*(1/Compaction_Ratio)),Slice_Volume=pi*(2.54^2)*Slice_Height_Corrected_cm)%>%
  mutate(Sample_Density_g_per_ml=Sample_Weight_gDW/Slice_Volume,
         Sediment_Density_g_per_ml=Sediment_Weight_gDW/Slice_Volume,
         Frac_Rhizome=Rhizome_gDW/Sample_Weight_gDW,
         Rhizome_Density_g_per_ml=Frac_Rhizome*Sample_Density_g_per_ml,)%>%
    dplyr::mutate(Factor=ifelse(Site=="SJBA" | Site=="SJBB" | Site=="SJBC" | Site=="SMARA" | Site=="SMARB" | Site=="SMARC" | Site=="STCHA" |Site=="STCHB" |Site=="STCHC" ,"Control","Seagrass"))%>%
  mutate(Percent_Shell=Frac_Pebbles*100,Percent_Gravel=Frac_Gravel*100,Percent_Coarse=Frac_Coarse_Sand*100,Percent_Medium=Frac_Medium_Sand*100,Percent_Fine=Frac_Fine_Sand*100,Percent_Silt=Frac_Silt*100)%>%
  dplyr::select(1:7,18,8,19:22,24:31)

names(Grainsize_QAQC)
write.csv(Grainsize_QAQC,file="data_output//Grainsize_Data_version_QAQC_10_6_2020.csv")


```


#Basic Plots
```{r}
names(LOI_QAQC)

ggplot(Compation_Ratio,aes(x=Compaction_Ratio))+geom_histogram()+xlab("Compaction Ratio") +ylab("Number of Cores")

ggplot(Compation_Ratio,aes(x=Core_Length_Corrected_cm))+geom_histogram()+xlab("Uncompressed Core Length (cm)") +ylab("Number of Cores")


ggplot(LOI_QAQC,aes(x=(Sediment_Depth_cm)))+geom_histogram(binwidth = 1)+xlab("Sediment Depth (cm)") +ylab("Number of Core Slices")


#Sediments
Grainsize_QAQC_long=Grainsize_QAQC%>%
  dplyr::select(1:2,12:21)%>%
  mutate(Percent_Sands=Percent_Coarse+Percent_Medium+Percent_Fine)%>%
  dplyr::select(1:8,12:13)%>%
  gather(key="Grainsize","Percent",7:10)

#Shell
ggplot(Grainsize_QAQC_long,aes(x=as.integer(Percent),fill=Grainsize))+geom_density(position = "dodge",alpha=0.25) + xlab("Percent Grainsize per Slice") + ylab("Frequency")

Grainsize_QAQC=Grainsize_QAQC%>%
  mutate(Percent_Sands=Percent_Coarse+Percent_Medium+Percent_Fine)


```


#Combinging analytical datasets 
```{r}
LOI_QAQC_By_Site_Slice=LOI_QAQC_Analyzed%>%
  group_by(Site,Factor,Quadrat,Bagged_Slice_Number,Slice_Number,Sediment_Depth_cm,Sediment_Depth_Group)%>%
  dplyr::summarize(OLOI=mean(OLOI,na.rm=TRUE),ILOI=mean(ILOI,na.rm=TRUE),Organic_Density_g_per_ml=mean(Organic_Density_g_per_ml,na.rm=TRUE),Inorganic_Density_g_per_ml=mean(Inorganic_Density_g_per_ml,na.rm=TRUE),Percent_Carbon=mean(Percent_Carbon,na.rm=TRUE),Rhizome_Density_g_per_ml=mean(Rhizome_Density_g_per_ml,na.rm=TRUE),Shell_Density_g_per_ml=mean(Shell_Density_g_per_ml,na.rm=TRUE))%>%
  ungroup()%>%
  filter(is.na(OLOI)==FALSE)%>%
  mutate(Organic_Carbon_Density_g_per_ml=(Percent_Carbon/100) * Organic_Density_g_per_ml,
         Inorganic_Carbon_Density_g_per_ml=(Inorganic_Density_g_per_ml* 0.12),
         Total_Carbon_Density_g_per_ml=Organic_Carbon_Density_g_per_ml+Inorganic_Carbon_Density_g_per_ml)

summary(LOI_QAQC_By_Site_Slice)

ggplot(LOI_QAQC_By_Site_Slice,aes(x=(Sediment_Depth_cm)))+geom_histogram(binwidth = 1)+xlab("Sediment Depth (cm)") +ylab("Frequency")


#OM %
ggplot(LOI_QAQC_By_Site_Slice,aes(x=as.integer(OLOI),fill=Factor),na.rm=TRUE)+geom_density(position="dodge",alpha=0.25,bw=2) + xlab("Sedimentary Organics Per Slice") + ylab("Number of Core Slices") +facet_wrap(~Sediment_Depth_Group,nrow=1) + ggtitle("Organic Matter by Sediment Depth Bin (%)")

ggplot(LOI_QAQC_By_Site_Slice,aes(y=as.integer(OLOI),fill=Factor),na.rm=TRUE)+geom_boxplot() + xlab(" Sedimentary Organics Per Slice") + ylab("Number of Core Slices") +facet_wrap(~Sediment_Depth_Group,nrow=2)+ ggtitle("Organic Matter by Sediment Depth Bin (%)")


#OM Density
ggplot(LOI_QAQC_By_Site_Slice,aes(y=as.integer(Organic_Density_g_per_ml*1000),fill=Factor),na.rm=TRUE)+geom_boxplot() + xlab("Organic Density of Slice") + ylab("Number of Core Slices") +facet_wrap(~Sediment_Depth_Group,nrow=2)+ ggtitle("Organic Density by Sediment Depth Bin (kg/ sqm)")

#IOM %
ggplot(LOI_QAQC_By_Site_Slice,aes(x=as.integer(ILOI),fill=Factor))+geom_density(position="dodge",alpha=0.25,bw=2) + xlab("Sedimetary Carbonates Per Slice") + ylab("Frequency")  +facet_wrap(~Sediment_Depth_Group,nrow=1) +ggtitle("Carbonates by Sediment Depth Bin (%)")

ggplot(LOI_QAQC_By_Site_Slice,aes(y=as.integer(ILOI),fill=Factor),na.rm=TRUE)+geom_boxplot() + xlab("Sedimentary Carbonates Per Slice") + ylab("Number of Core Slices") +facet_wrap(~Sediment_Depth_Group,nrow=2)+ggtitle("Carbonates by Sediment Depth Bin (%)")

#Inorganic Density
ggplot(LOI_QAQC_By_Site_Slice,aes(y=as.integer(Inorganic_Density_g_per_ml*1000),fill=Factor),na.rm=TRUE)+geom_boxplot() + xlab("Carbonate Density of Slice") + ylab("Number of Core Slices") +facet_wrap(~Sediment_Depth_Group,nrow=2)+ ggtitle("Carbonate Density by Sediment Depth Bin (kg/ sqm)")

#%C
ggplot(LOI_QAQC_By_Site_Slice,aes(x=Percent_Carbon,fill=Factor))+geom_density(position="dodge",alpha=0.25,bw=1) + xlab("Organic Carbon Per Slice") + ylab("Frequency") +facet_wrap(~Sediment_Depth_Group) +ggtitle("Organic Carbon by Sediment Depth Bin (%)")

ggplot(LOI_QAQC_By_Site_Slice,aes(y=as.integer(Percent_Carbon),fill=Factor),na.rm=TRUE)+geom_boxplot() + xlab("Organic Carbon Per Slice") + ylab("Number of Core Slices") +facet_wrap(~Sediment_Depth_Group,nrow=2)+ggtitle("Organic Carbon by Sediment Depth Bin (%)")

#Organic Carbon Density
ggplot(LOI_QAQC_By_Site_Slice,aes(y=as.integer(Organic_Carbon_Density_g_per_ml*1000),fill=Factor),na.rm=TRUE)+geom_boxplot() + xlab("Organic Carbon Density of Slice") + ylab("Number of Core Slices") +facet_wrap(~Sediment_Depth_Group,nrow=2)+ ggtitle("Organic Carbon Density by Sediment Depth Bin (kg/ sqm)")

#Total Carbon Density
ggplot(LOI_QAQC_By_Site_Slice,aes(y=as.integer(Total_Carbon_Density_g_per_ml*1000),fill=Factor),na.rm=TRUE)+geom_boxplot() + xlab("Total Caron Density of Slice") + ylab("Number of Core Slices") +facet_wrap(~Sediment_Depth_Group,nrow=2)+ ggtitle("Total Carbon Density by Sediment Depth Bin (kg/ sqm)")


## BY DEPTH

# Percent OLOI
ggplot(LOI_QAQC_By_Site_Slice,aes(y=as.integer(OLOI),x=-Sediment_Depth_cm,color=Factor),na.rm=TRUE)+geom_point() + geom_smooth() + ylab("OM % of Slice") + xlab("Number of Core Slices") + ggtitle("Organic Matter by Sediment Deph (kg/ sqm)")+coord_flip()

ggplot(LOI_QAQC_By_Site_Slice,aes(y=as.integer(ILOI),x=-Sediment_Depth_cm,color=Factor),na.rm=TRUE)+geom_point() + geom_smooth() + ylab("Carbonates % of Slice") + xlab("Number of Core Slices") + ggtitle("Carbonates by Sediment Deph (kg/ sqm)")+coord_flip()

#Organic Carbon Density
ggplot(LOI_QAQC_By_Site_Slice,aes(y=as.integer(Organic_Carbon_Density_g_per_ml*1000),x=-Sediment_Depth_cm,color=Factor),na.rm=TRUE)+geom_point() + geom_smooth() + ylab("Total Caron Density of Slice") + xlab("Number of Core Slices") + ggtitle("Organic Carbon Density by Sediment Deph (kg/ sqm)")+coord_flip()



#Total Carbon Density
ggplot(LOI_QAQC_By_Site_Slice,aes(y=as.integer(Total_Carbon_Density_g_per_ml*1000),x=-Sediment_Depth_cm,color=Factor),na.rm=TRUE)+geom_point() + geom_smooth() + ylab("Total Carbon Density of Slice") + xlab("Number of Core Slices") + ggtitle("Total Carbon Density by Sediment Deph (kg/ sqm)")+coord_flip()



LOI_QAQC_By_Site=LOI_QAQC_By_Site_Slice%>%
  dplyr::group_by(Site,Factor,Quadrat)%>%
  dplyr::summarize(OLOI=mean(OLOI,na.rm=TRUE),
                   ILOI=mean(ILOI,na.rm=TRUE),
                   Carbon=mean(Percent_Carbon,na.rm=TRUE),
                   Organic_Density_g_per_ml=mean(Organic_Density_g_per_ml,na.rm=TRUE),
                   Inorganic_Density_g_per_ml=mean(Inorganic_Density_g_per_ml,na.rm=TRUE),
                   Rhizome_Density_g_per_ml=mean(Rhizome_Density_g_per_ml,na.rm=TRUE),
                   Shell_Density_g_per_ml=mean(Shell_Density_g_per_ml,na.rm=TRUE),
                   Organic_Carbon_Density_g_per_ml=mean(Organic_Carbon_Density_g_per_ml,na.rm=TRUE),
                   Inorganic_Carbon_Density_g_per_ml=mean(Inorganic_Carbon_Density_g_per_ml,na.rm=TRUE))%>%
                  dplyr::mutate(Rhizome_Stock_kg_per_sqm=sum(Rhizome_Density_g_per_ml)*(1/1000)*(10e6)*1000*50,    
                         Shell_Stock_kg_per_sqm=mean(Shell_Density_g_per_ml)*(1/1000)*(10e6)*1000*50,                           Organic_Carbon_Stock_kg_per_sqm=mean(Organic_Carbon_Density_g_per_ml)*(1/1000)*(10e6)*1000*50,
                   Inorganic_Carbon_Stock_kg_per_sqm=mean(Inorganic_Carbon_Density_g_per_ml)*(1/1000)*(10e6)*1000*50)%>%
  ungroup()%>%
  dplyr::group_by(Site,Factor)%>%
  dplyr::summarize(OLOI=mean(OLOI,na.rm=TRUE),
                   ILOI=mean(ILOI,na.rm=TRUE),
                   Carbon=mean(Carbon,na.rm=TRUE),
                   Rhizome_Stock_g_per_sqm=mean(Rhizome_Stock_kg_per_sqm,na.rm=TRUE)*(1/1000),
                   Shell_Stock_g_per_sqm=mean(Shell_Stock_kg_per_sqm,na.rm=TRUE)*(1/1000),
                   Organic_Carbon_Stock_g_per_sqm=mean(Organic_Carbon_Stock_kg_per_sqm,na.rm=TRUE)*(1/1000),
                   Inorganic_Carbon_Stock_g_per_sqm=mean(Inorganic_Carbon_Stock_kg_per_sqm,na.rm=TRUE)*(1/1000))%>%
      ungroup()



seagrass_surveys_By_Site=seagrass_surveys%>%
  group_by(Region,Site,Quadrat,Cover_Level)%>%
  dplyr::summarize(SAV_Cover=mean(SAV_Cover,na.rm=TRUE),Secchi_m=mean(Secchi_m,na.rm=TRUE),Depth_m=mean(Depth_m,na.rm=TRUE),Thalassia.testudinum=mean(Thalassia.testudinum,na.rm=TRUE),Syringodium.filiforme=mean(Syringodium.filiforme,na.rm=TRUE),Halodule.wrightii=mean(Halodule.wrightii,na.rm=TRUE),Seagrass_Spp=mean(Seagrass_Spp,na.rm=TRUE),Algal_Spp=mean(Algal_Spp,na.rm=TRUE))%>%
  ungroup()%>%
  group_by(Region,Site,Cover_Level)%>%
  dplyr::summarize(SAV_Cover=mean(SAV_Cover,na.rm=TRUE),Secchi_m=mean(Secchi_m,na.rm=TRUE),Depth_m=mean(Depth_m,na.rm=TRUE),Thalassia.testudinum=mean(Thalassia.testudinum,na.rm=TRUE),Syringodium.filiforme=mean(Syringodium.filiforme,na.rm=TRUE),Halodule.wrightii=mean(Halodule.wrightii,na.rm=TRUE),Seagrass_Spp=mean(Seagrass_Spp,na.rm=TRUE),Algal_Spp=mean(Algal_Spp,na.rm=TRUE))%>%
  ungroup()


Environmental_Factors_Sites=seagrass_surveys%>%
  dplyr::select(Site,Latitude,Longitude,Salinity.Min,Nitrate.Mean,Light.bottom.Min,Par.Mean,Dist_To_River,Dist_To_Shore)%>%
  group_by(Site)%>%
  dplyr::summarize(Latitude=mean(Latitude,na.rm=TRUE),Longitude=mean(Longitude,na.rm=TRUE),Salinity.Min=mean(Salinity.Min,na.rm=TRUE),Nitrate.Mean=mean(Nitrate.Mean,na.rm=TRUE),Light.bottom.Min=mean(Light.bottom.Min,na.rm=TRUE),Par.Mean=mean(Par.Mean,na.rm=TRUE),Dist_To_River=mean(Dist_To_River,na.rm=TRUE),Dist_To_Shore=mean(Dist_To_Shore,na.rm=TRUE))%>%
  ungroup()


seagrass_surveys_By_Site=join(seagrass_surveys_By_Site,Environmental_Factors_Sites,by="Site")

Grainsize_QAQC_By_Site_Slice=Grainsize_QAQC%>%
  group_by(Site,Slice_Number)%>%
  dplyr::summarize(Percent_Shell=mean(Percent_Shell,na.rm=TRUE),Percent_Gravel=mean(Percent_Gravel,na.rm=TRUE),Percent_Coarse=mean(Percent_Coarse,na.rm=TRUE),Percent_Medium=mean(Percent_Medium,na.rm=TRUE),Percent_Fine=mean(Percent_Fine,na.rm=TRUE),Percent_Silt=mean(Percent_Silt,na.rm=TRUE),Percent_Sands=mean(Percent_Sands,na.rm=TRUE))%>%
  ungroup()


Grainsize_QAQC_By_Site=Grainsize_QAQC%>%
  group_by(Site)%>%
  dplyr::summarize(Percent_Shell=mean(Percent_Shell,na.rm=TRUE),Percent_Gravel=mean(Percent_Gravel,na.rm=TRUE),Percent_Coarse=mean(Percent_Coarse,na.rm=TRUE),Percent_Medium=mean(Percent_Medium,na.rm=TRUE),Percent_Fine=mean(Percent_Fine,na.rm=TRUE),Percent_Silt=mean(Percent_Silt,na.rm=TRUE),Percent_Sands=mean(Percent_Sands,na.rm=TRUE))%>%
  ungroup()
names(Grainsize_QAQC_By_Site)



#MAKING THE BLUE CARBON DATASET 

BlueCarbon_QAQC=plyr::join(seagrass_surveys_By_Site,LOI_QAQC_By_Site,by=c("Site"),match="all",type="inner")

names(BlueCarbon_QAQC)

BlueCarbon_QAQC=plyr::join(BlueCarbon_QAQC,Grainsize_QAQC_By_Site,by=c("Site"),match="all",type="inner")
names(BlueCarbon_QAQC)

BlueCarbon_QAQC=BlueCarbon_QAQC%>%
  mutate(Cover_Level=ifelse(SAV_Cover>=50,"high",ifelse(SAV_Cover<50 | SAV_Cover>0,"low","none")))%>%
  mutate(TH_PA=ifelse(Thalassia.testudinum>0,1,0),SY_PA=ifelse(Syringodium.filiforme>0,1,0),HA_PA=ifelse(Halodule.wrightii>0,1,0),TH_PA=as.factor(TH_PA),SY_PA=as.factor(SY_PA),HA_PA=as.factor(HA_PA))

summary(BlueCarbon_QAQC)

#%OM
BlueCarbon_QAQC%>%
  group_by(Factor)%>%
  # dplyr::summarize(OLOI=mean(OLOI,na.rm=TRUE),ILOI=mean(ILOI,na.rm=TRUE))%>%
  ggplot(aes(x=Factor,y=OLOI))+geom_boxplot()+xlab("Survey Strata")+ylab("Average Percent Organic Matter")

#%IOM
BlueCarbon_QAQC%>%
  group_by(Factor)%>%
  # dplyr::summarize(ILOI=mean(ILOI,na.rm=TRUE))%>%
  ggplot(aes(x=Factor,y=ILOI))+geom_boxplot() +xlab("Survey Strata")+ylab("Average Percent Sedimentary Carbonates")

# Carbon Stock
BlueCarbon_QAQC%>%
  group_by(Factor)%>%
  # dplyr::summarize(OLOI=mean(OLOI,na.rm=TRUE),ILOI=mean(ILOI,na.rm=TRUE))%>%
  ggplot(aes(x=Factor,y=Organic_Carbon_Stock_g_per_sqm))+geom_boxplot()+xlab("Survey Strata")+ylab("Average Organic Carbon Stock (g/sqm)")

# Inorganic Carbon Stock
BlueCarbon_QAQC%>%
  group_by(Factor)%>%
  # dplyr::summarize(OLOI=mean(OLOI,na.rm=TRUE),ILOI=mean(ILOI,na.rm=TRUE))%>%
  ggplot(aes(x=Factor,y=Inorganic_Carbon_Stock_g_per_sqm))+geom_boxplot()+xlab("Survey Strata")+ylab("Average Inorganic Carbon Stock (g/sqm)")


# Rhizome g/sqm
BlueCarbon_QAQC%>%
  group_by(Factor)%>%
  # dplyr::summarize(OLOI=mean(OLOI,na.rm=TRUE),ILOI=mean(ILOI,na.rm=TRUE))%>%
  ggplot(aes(x=Factor,y=Rhizome_Stock_g_per_sqm))+geom_boxplot()+xlab("Survey Strata")+ylab("Average Rhizome Carbon Stock (g/sqm)")

# SHell g/sqm
BlueCarbon_QAQC%>%
  group_by(Factor)%>%
  # dplyr::summarize(OLOI=mean(OLOI,na.rm=TRUE),ILOI=mean(ILOI,na.rm=TRUE))%>%
  ggplot(aes(x=Factor,y=Shell_Stock_g_per_sqm))+geom_boxplot()+xlab("Survey Strata")+ylab("Average Shell Stock (g/sqm)")

# Seagrass Cover 
ggplot(BlueCarbon_QAQC,aes(x=SAV_Cover,y=OLOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=SAV_Cover,y=ILOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Seagrass_Spp,y=OLOI))+ geom_point() +geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Seagrass_Spp,y=ILOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Algal_Spp,y=OLOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Algal_Spp,y=ILOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Thalassia.testudinum,y=OLOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Thalassia.testudinum,y=ILOI))+ geom_point()+geom_smooth(method="gam")

BlueCarbon_QAQC%>%
  mutate(TH_PA=as.factor(TH_PA))%>%
  dplyr::filter(Factor=="Seagrass")%>%
  ggplot(aes(y=OLOI,x=TH_PA,fill=TH_PA)) + geom_boxplot()


ggplot(BlueCarbon_QAQC,aes(x=Syringodium.filiforme,y=OLOI))+ geom_point()+geom_smooth(method="gam")
ggplot(BlueCarbon_QAQC,aes(x=Syringodium.filiforme,y=ILOI))+ geom_point()+geom_smooth(method="gam")

BlueCarbon_QAQC%>%
  mutate(SY_PA=as.factor(SY_PA))%>%
  dplyr::filter(Factor=="Seagrass")%>%
  ggplot(aes(y=OLOI,x=SY_PA,fill=SY_PA)) + geom_boxplot()

ggplot(BlueCarbon_QAQC,aes(x=Halodule.wrightii,y=OLOI))+ geom_point()+geom_smooth(method="gam")
ggplot(BlueCarbon_QAQC,aes(x=Halodule.wrightii,y=ILOI))+ geom_point()+geom_smooth(method="gam")


BlueCarbon_QAQC%>%
  mutate(HA_PA=as.factor(HA_PA))%>%
  dplyr::filter(Factor=="Seagrass")%>%
  ggplot(aes(y=OLOI,x=HA_PA,fill=HA_PA)) + geom_boxplot()

ggplot(BlueCarbon_QAQC,aes(x=Secchi_m,y=OLOI))+ geom_point()+geom_smooth(method="gam")
ggplot(BlueCarbon_QAQC,aes(x=Secchi_m,y=ILOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Depth_m,y=OLOI))+ geom_point()+geom_smooth(method="gam")
ggplot(BlueCarbon_QAQC,aes(x=Depth_m,y=ILOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Percent_Shell,y=OLOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Percent_Gravel,y=OLOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Percent_Sands,y=OLOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Percent_Silt,y=OLOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Salinity.Min,y=OLOI))+ geom_point()+geom_smooth(method="gam")
ggplot(BlueCarbon_QAQC,aes(x=Salinity.Min,y=ILOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Nitrate.Mean,y=OLOI))+ geom_point()+geom_smooth(method="gam")
ggplot(BlueCarbon_QAQC,aes(x=Nitrate.Mean,y=ILOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Light.bottom.Min,y=OLOI))+ geom_point()+geom_smooth(method="gam")
ggplot(BlueCarbon_QAQC,aes(x=Light.bottom.Min,y=ILOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Par.Mean,y=OLOI))+ geom_point()+geom_smooth(method="gam")
ggplot(BlueCarbon_QAQC,aes(x=Par.Mean,y=ILOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Dist_To_River,y=OLOI))+ geom_point()+geom_smooth(method="gam")
ggplot(BlueCarbon_QAQC,aes(x=Dist_To_River,y=ILOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Dist_To_Shore,y=OLOI))+ geom_point()+geom_smooth(method="gam")
ggplot(BlueCarbon_QAQC,aes(x=Dist_To_Shore,y=ILOI))+ geom_point()+geom_smooth(method="gam")

ggplot(BlueCarbon_QAQC,aes(x=Latitude,y=OLOI))+ geom_point()+geom_smooth(method="gam")
ggplot(BlueCarbon_QAQC,aes(x=Longitude,y=OLOI))+ geom_point()+geom_smooth(method="gam")


 BlueCarbon_QAQC%>%
   dplyr::group_by(Region)%>%
   dplyr::summarize(Nitrates=mean(Nitrate.Mean,na.rm=TRUE), Depth=mean(Depth_m,na.rm=TRUE), Secchi_m=mean(Secchi_m,na.rm=TRUE),Dist_To_Shore=mean(Dist_To_Shore,na.rm=TRUE),Dist_To_River=mean(Dist_To_River,na.rm=TRUE),Light=mean(Light.bottom.Min,na.rm=TRUE))

```

#GAM % Organic Matter
```{r}

library(mgcv)

Seagrass_model=gam(OLOI~ s(Seagrass_Spp,bs="ts",k=4)+s(Thalassia.testudinum,bs="ts",k=4)+s(Syringodium.filiforme,bs="ts",k=4)+s(Halodule.wrightii,bs="ts",k=4)+as.factor(Factor)+as.factor(TH_PA)+ as.factor(SY_PA)+ as.factor(HA_PA),data=BlueCarbon_QAQC, method="ML")
summary(Seagrass_model)
plot.gam(Seagrass_model,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)

Seagrass_model_2=gam(OLOI~ s(Seagrass_Spp,bs="ts",k=4)+s(Thalassia.testudinum,bs="ts",k=4)+s(Halodule.wrightii,bs="ts",k=4)+as.factor(Factor)+as.factor(TH_PA)+ as.factor(SY_PA)+ as.factor(HA_PA),data=BlueCarbon_QAQC, method="ML")
summary(Seagrass_model_2)
plot.gam(Seagrass_model_2,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)

Seagrass_model_3=gam(OLOI~ s(Seagrass_Spp,bs="ts",k=4)+s(Halodule.wrightii,bs="ts",k=4)+as.factor(Factor)+as.factor(TH_PA)+ as.factor(SY_PA)+ as.factor(HA_PA),data=BlueCarbon_QAQC, method="ML")
summary(Seagrass_model_3)
plot.gam(Seagrass_model_3,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)


Seagrass_model_4=gam(OLOI~ s(Seagrass_Spp,bs="ts",k=4)+s(Halodule.wrightii,bs="ts",k=4)+as.factor(Factor)+as.factor(SY_PA)+ as.factor(HA_PA),data=BlueCarbon_QAQC, method="ML")
summary(Seagrass_model_4)
plot.gam(Seagrass_model_4,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)


Seagrass_model_5=gam(OLOI~as.factor(Factor)+as.factor(SY_PA)+ as.factor(HA_PA),data=BlueCarbon_QAQC,method="ML")
summary(Seagrass_model_5)
plot.gam(Seagrass_model_5,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)

AIC(Seagrass_model,Seagrass_model_2,Seagrass_model_3,Seagrass_model_4,Seagrass_model_5)

Secchi_model=gam(OLOI~ s(Secchi_m,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Secchi_model)
plot(Secchi_model)

Depth_model=gam(OLOI~ s(Depth_m,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Depth_model)
plot(Depth_model)

Seagrass_Spp_Cover_model=gam(OLOI~ s(Seagrass_Spp,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Seagrass_Spp_Cover_model)
plot(Seagrass_Spp_Cover_model)

Sand_model=gam(OLOI~ s(Percent_Coarse,bs="ts",k=4) +s(Percent_Medium,bs="ts",k=4)+s(Percent_Fine,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Sand_model)
plot(Sand_model,trans=exp)

Sediment_model=gam(OLOI~ s(Percent_Gravel,bs="ts",k=4)+ s(Percent_Coarse,bs="ts",k=4) +s(Percent_Medium,bs="ts",k=4)+s(Percent_Fine,bs="ts",k=4) +s(Percent_Gravel,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Sediment_model)
plot(Sediment_model,trans=exp)

Silt_model=gam(OLOI~ s(Percent_Silt,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Silt_model)
plot(Silt_model,trans=exp)

Nitrate_Mean_model=gam(OLOI~ s(Nitrate.Mean,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Nitrate_Mean_model)
plot(Nitrate_Mean_model,trans=exp)

Par_Mean_model=gam(OLOI~ s(Par.Mean,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Par_Mean_model)
plot(Par_Mean_model,trans=exp)

Light_Min_model=gam(OLOI~ s(Light.bottom.Min,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Light_Min_model)
plot(Light_Min_model,trans=exp)

Dist_To_Shore_model=gam(OLOI~ s(Dist_To_Shore,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Dist_To_Shore_model)
plot(Dist_To_Shore_model,trans=exp)

Dist_from_River_Shore_model=gam(OLOI~ s(Dist_To_River,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Dist_from_River_Shore_model)
plot(Dist_from_River_Shore_model,trans=exp)

Treatment_Mean_model=gam(OLOI~ Factor, data=BlueCarbon_QAQC,method="ML")
summary(Treatment_Mean_model)
# plot.gam(Treatment_Mean_model,trans=exp,all.terms=TRUE)

TH_PA_model=gam(OLOI~ TH_PA, data=BlueCarbon_QAQC,method="ML")
summary(TH_PA_model)

SPP_PA_model=gam(OLOI~ TH_PA + HA_PA, data=BlueCarbon_QAQC,method="ML")
summary(SPP_PA_model)

AIC(Seagrass_model,Seagrass_model_2,Seagrass_model_3,Seagrass_model_4,Seagrass_model_5,Secchi_model,Depth_model,Seagrass_Spp_Cover_model,Sand_model,Silt_model,Sediment_model,Nitrate_Mean_model,Treatment_Mean_model,TH_PA_model,SPP_PA_model)
# 
# full_model=gam(OLOI~ s(Seagrass_Spp,bs="ts",k=4) + s(Dist_To_River,bs="ts",k=4) + +s(Percent_Coarse,bs="ts",k=4) + s(Depth_m,bs="ts",k=4) +as.factor(Factor) + as.factor(TH_PA)+ as.factor(SY_PA) + as.factor(HA_PA), data=BlueCarbon_QAQC,method="ML",family="tw")
# 
# summary(full_model)
# plot.gam(full_model,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)
# 
# v1=gam(OLOI~ s(Seagrass_Spp,bs="ts",k=4) + s(Dist_To_River,bs="ts",k=4) +s(Percent_Coarse,bs="ts",k=4)+Factor + as.factor(TH_PA)+ as.factor(SY_PA) + as.factor(HA_PA), data=BlueCarbon_QAQC,method="ML",family="tw")
# 
# summary(v1)
# plot.gam(v1,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)
# 
# 
# v2=gam(OLOI~ s(Seagrass_Spp,bs="ts",k=4) + s(Dist_To_River,bs="ts",k=4) + as.factor(Factor)+as.factor(HA_PA), data=BlueCarbon_QAQC,method="ML",family="tw")
# 
# summary(v2)
# 
# plot.gam(v2,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)
# 
# v3=gam(OLOI~ s(Seagrass_Spp,bs="ts",k=4) + s(Dist_To_River,bs="ts",k=4) + HA_PA, data=BlueCarbon_QAQC,method="ML",family="tw")
# 
# plot.gam(v3,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)
# 
# 
# v4=gam(OLOI~te(Seagrass_Spp,Dist_To_River,bs="ts"), data=BlueCarbon_QAQC,method="ML",family="tw")
# 
# summary(v4)
# 
# plot.gam(v4,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)
# 
AIC(Secchi_model,Depth_model,Seagrass_Spp_Cover_model,Sand_model,Silt_model,Sediment_model,Nitrate_Mean_model,Treatment_Mean_model,TH_PA_model,SPP_PA_model,v1,v2,v3,v4)


```


#Finding the best model for %Organic Matter
```{r}
library(FSSgam)
names(BlueCarbon_QAQC)

#Model Selection 
##################################################################################
cat.preds=c("TH_PA","SY_PA","HA_PA","Factor")
null.vars=c("Region","Site")
cont.preds=c("Depth_m","Dist_To_Shore","Dist_To_River","Nitrate.Mean",
             "Rhizome_Stock_g_per_sqm",
             "Thalassia.testudinum", "Syringodium.filiforme",
             "Halodule.wrightii","Seagrass_Spp",
             "Percent_Coarse","Percent_Medium","Percent_Silt")

BlueCarbon_QAQC=BlueCarbon_QAQC[complete.cases(BlueCarbon_QAQC),]
BlueCarbon_QAQC=BlueCarbon_QAQC%>%
  mutate(TH_PA=as.factor(TH_PA),SY_PA=as.factor(SY_PA),HA_PA=as.factor(HA_PA),Factor=as.factor(Factor))

OLOI_gam_base=mgcv::gam(OLOI ~ 1,data=BlueCarbon_QAQC, method="ML")


model.set.OLOI=generate.model.set(use.dat=BlueCarbon_QAQC, 
                                  test.fit=OLOI_gam_base,
                          pred.vars.cont=cont.preds,
                          # cyclic.vars="month",
                          pred.vars.fact=cat.preds,
                          # null.terms = null.vars,
                          # factor.factor.interactions = TRUE,
                          smooth.smooth.interactions = TRUE,
                          cov.cutoff = 0.50,
                          max.predictors = 5,
                          k=4, bs.arg="'ts'")


out.list.OLOI=fit.model.set(model.set.OLOI)


#examine the output
names(out.list.OLOI)
out.list.OLOI$failed.models
length(out.list.OLOI$success.models)
mod.table.OLOI=out.list.OLOI$mod.data.out
mod.table.OLOI=mod.table.OLOI[order(mod.table.OLOI$AICc),]
head(mod.table.OLOI)

OLOI_ModelTable=mod.table.OLOI

write.csv(OLOI_ModelTable,file ="model_output/OLOIModelTable.csv")

final_model_OLOI=mgcv::gam(OLOI ~ HA_PA + SY_PA + s(Nitrate.Mean, by=HA_PA,bs="ts",k=4) + s(Seagrass_Spp,by=SY_PA,bs="ts",k=4),data=BlueCarbon_QAQC, method="ML")

summary(final_model_OLOI)

plot.gam(final_model_OLOI,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)

final_model_OLOI_v2=mgcv::gam(OLOI ~ HA_PA + SY_PA + s(Nitrate.Mean,bs="ts",k=4) + s(Seagrass_Spp,by=SY_PA,bs="ts",k=4),data=BlueCarbon_QAQC, method="ML")

summary(final_model_OLOI_v2)

plot.gam(final_model_OLOI_v2,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)


final_model_OLOI_v3=mgcv::gam(OLOI ~ HA_PA + s(Nitrate.Mean,bs="ts",k=4) + s(Seagrass_Spp,bs="ts",k=4) + HA_PA,data=BlueCarbon_QAQC, method="ML")

summary(final_model_OLOI_v3)

plot.gam(final_model_OLOI_v3,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)

final_model_OLOI_v4=mgcv::gam(OLOI ~ HA_PA + s(Dist_To_River,bs="ts",k=4) + s(Seagrass_Spp,bs="ts",k=4) ,data=BlueCarbon_QAQC, method="ML")

summary(final_model_OLOI_v4)

plot.gam(final_model_OLOI_v4,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)

final_model_OLOI_v5=mgcv::gam(OLOI ~ s(Dist_To_River,bs="ts",k=4) + te(Seagrass_Spp,Nitrate.Mean,bs="ts",k=4) + HA_PA,data=BlueCarbon_QAQC, method="ML")

summary(final_model_OLOI_v5)

plot.gam(final_model_OLOI_v5,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)

AIC(final_model_OLOI,final_model_OLOI_v2,final_model_OLOI_v3,final_model_OLOI_v4,final_model_OLOI_v5)
```



#GAM Organic Carbon Stock
```{r}
library(mgcv)

Seagrass_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ s(Seagrass_Spp,bs="ts",k=4)+
                         s(Thalassia.testudinum,bs="ts",k=4)+
                         s(Syringodium.filiforme,bs="ts",k=4)+
                         s(Halodule.wrightii,bs="ts",k=4)+
                         as.factor(Factor)+
                         as.factor(TH_PA)+ 
                         as.factor(SY_PA)+ 
                         as.factor(HA_PA),data=BlueCarbon_QAQC, method="ML")
summary(Seagrass_model_OCD)
plot.gam(Seagrass_model_OCD,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)

Seagrass_model_OCD_2=gam(Organic_Carbon_Stock_g_per_sqm~ 
                           # s(Seagrass_Spp,bs="ts",k=4)+
                         s(Thalassia.testudinum,bs="ts",k=4)+
                         s(Syringodium.filiforme,bs="ts",k=4)+
                         s(Halodule.wrightii,bs="ts",k=4)+
                         as.factor(Factor)+
                         as.factor(TH_PA)+ 
                         as.factor(SY_PA)+ 
                         as.factor(HA_PA),data=BlueCarbon_QAQC, method="ML")
summary(Seagrass_model_OCD_2)
# plot.gam(Seagrass_model_OCD_2,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)

Seagrass_model_OCD_3=gam(Organic_Carbon_Stock_g_per_sqm~ 
                           # s(Seagrass_Spp,bs="ts",k=4)+
                         s(Thalassia.testudinum,bs="ts",k=4)+
                         # s(Syringodium.filiforme,bs="ts",k=4)+
                         s(Halodule.wrightii,bs="ts",k=4)+
                         as.factor(Factor)+
                         as.factor(TH_PA)+ 
                         as.factor(SY_PA)+ 
                         as.factor(HA_PA),data=BlueCarbon_QAQC, method="ML")
summary(Seagrass_model_OCD_3)
plot.gam(Seagrass_model_OCD_3,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)


Seagrass_model_OCD_4=gam(Organic_Carbon_Stock_g_per_sqm~ 
                           # s(Seagrass_Spp,bs="ts",k=4)+
                         # s(Thalassia.testudinum,bs="ts",k=4)+
                         # s(Syringodium.filiforme,bs="ts",k=4)+
                         s(Halodule.wrightii,bs="ts",k=4)+
                         as.factor(Factor)+
                         as.factor(TH_PA)+ 
                         as.factor(SY_PA)+ 
                         as.factor(HA_PA),data=BlueCarbon_QAQC, method="ML")
summary(Seagrass_model_OCD_4)
plot.gam(Seagrass_model_OCD_4,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)


Seagrass_model_OCD_5=gam(Organic_Carbon_Stock_g_per_sqm~ 
                           # s(Seagrass_Spp,bs="ts",k=4)+
                         # s(Thalassia.testudinum,bs="ts",k=4)+
                         # s(Syringodium.filiforme,bs="ts",k=4)+
                         # s(Halodule.wrightii,bs="ts",k=4)+
                         as.factor(Factor)+
                         as.factor(TH_PA)+ 
                         as.factor(SY_PA)+
                         as.factor(HA_PA),data=BlueCarbon_QAQC, method="ML")
summary(Seagrass_model_OCD_5)
plot.gam(Seagrass_model_5,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)


Seagrass_model_OCD_6=gam(Organic_Carbon_Stock_g_per_sqm~ 
                           # s(Seagrass_Spp,bs="ts",k=4)+
                         # s(Thalassia.testudinum,bs="ts",k=4)+
                         # s(Syringodium.filiforme,bs="ts",k=4)+
                         # s(Halodule.wrightii,bs="ts",k=4)+
                         as.factor(Factor)+
                         # as.factor(TH_PA)+ 
                         as.factor(SY_PA)+
                         as.factor(HA_PA),data=BlueCarbon_QAQC, method="ML")
summary(Seagrass_model_OCD_6)
plot.gam(Seagrass_model_OCD_6,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)



Seagrass_model_OCD_7=gam(Organic_Carbon_Stock_g_per_sqm~ 
                           # s(Seagrass_Spp,bs="ts",k=4)+
                         # s(Thalassia.testudinum,bs="ts",k=4)+
                         # s(Syringodium.filiforme,bs="ts",k=4)+
                         # s(Halodule.wrightii,bs="ts",k=4)+
                         as.factor(Factor)+
                         # as.factor(TH_PA)+ 
                         # as.factor(SY_PA)+
                         as.factor(HA_PA),data=BlueCarbon_QAQC, method="ML")
summary(Seagrass_model_OCD_7)
plot.gam(Seagrass_model_OCD_7,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)
gam.check(Seagrass_model_OCD_7)

AIC(Seagrass_model_OCD,Seagrass_model_OCD_2,Seagrass_model_OCD_3,Seagrass_model_OCD_4,Seagrass_model_OCD_5,Seagrass_model_OCD_6,Seagrass_model_OCD_7)

Secchi_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ s(Secchi_m,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Secchi_model_OCD)
plot(Secchi_model_OCD)

Depth_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ s(Depth_m,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Depth_model_OCD)
plot(Depth_model_OCD)
# 
Seagrass_Spp_Cover_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ s(Seagrass_Spp,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Seagrass_Spp_Cover_model_OCD)
plot(Seagrass_Spp_Cover_model_OCD)

Sand_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ s(Percent_Coarse,bs="ts",k=4) +s(Percent_Medium,bs="ts",k=4)+s(Percent_Fine,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Sand_model_OCD)
# plot(Sand_model,trans=exp)
# 
Sediment_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ s(Percent_Gravel,bs="ts",k=4)+ s(Percent_Coarse,bs="ts",k=4) +s(Percent_Medium,bs="ts",k=4)+s(Percent_Fine,bs="ts",k=4) +s(Percent_Gravel,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Sediment_model_OCD)
plot(Sediment_model_OCD,trans=exp)

Silt_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ s(Percent_Silt,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Silt_model_OCD)
plot(Silt_model_OCD)

Nitrate_Mean_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ s(Nitrate.Mean,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Nitrate_Mean_model_OCD)
plot(Nitrate_Mean_model_OCD,trans=exp)

Par_Mean_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ s(Par.Mean,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Par_Mean_model_OCD)
plot(Par_Mean_model,trans=exp)

Light_Min_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ s(Light.bottom.Min,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Light_Min_model_OCD)
plot(Light_Min_model_OCD,trans=exp)

Dist_To_Shore_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ s(Dist_To_Shore,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Dist_To_Shore_model_OCD)
plot(Dist_To_Shore_model_OCD,trans=exp)

Dist_from_River_Shore_model_OCD=gam(Organic_Density_kg_per_m3~ s(Dist_To_River,bs="ts",k=4), data=BlueCarbon_QAQC,method="ML")
summary(Dist_from_River_Shore_model_OCD)
plot(Dist_from_River_Shore_model_OCD)

Treatment_Mean_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ Factor, data=BlueCarbon_QAQC,method="ML")
summary(Treatment_Mean_model_OCD)
plot.gam(Treatment_Mean_model,trans=exp,all.terms=TRUE)

TH_PA_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ TH_PA, data=BlueCarbon_QAQC,method="ML")
summary(TH_PA_model_OCD)

SPP_PA_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ TH_PA + HA_PA +SY_PA, data=BlueCarbon_QAQC,method="ML")
summary(SPP_PA_model_OCD)

AIC(Seagrass_model_OCD_7,Secchi_model_OCD,Depth_model_OCD,Seagrass_Spp_Cover_model_OCD,Sand_model_OCD,Silt_model_OCD,Sediment_model_OCD,Nitrate_Mean_model_OCD,Treatment_Mean_model_OCD,TH_PA_model_OCD,SPP_PA_model_OCD)
# 

full_model_OCD=gam(Organic_Carbon_Stock_g_per_sqm ~ s(Seagrass_Spp,bs="ts",k=4) +
                     s(Nitrate.Mean,bs="ts",k=4)+
                     s(Dist_To_Shore,bs="ts",k=4) +
                     s(Dist_To_River,bs="ts",k=4) +
                     s(Percent_Silt,bs="ts",k=4) + 
                     s(Depth_m,bs="ts",k=4) +
                    s(Rhizome_Stock_g_per_sqm,bs="ts",k=4)+

                                  as.factor(Factor) +
                     as.factor(HA_PA), data=BlueCarbon_QAQC,method="ML")

summary(full_model_OCD)
plot.gam(full_model_OCD,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)

v1_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ 
             s(Seagrass_Spp,bs="ts",k=4) +
                     # s(Nitrate.Mean,bs="ts",k=4)+
                     s(Dist_To_Shore,bs="ts",k=4) +
                     s(Dist_To_River,bs="ts",k=4) +
                     s(Percent_Silt,bs="ts",k=4) + 
                                  s(Rhizome_Stock_g_per_sqm,bs="ts",k=4)+

                     s(Depth_m,bs="ts",k=4) +
                     as.factor(Factor) +
                     as.factor(HA_PA), data=BlueCarbon_QAQC,method="ML")

summary(v1_OCD)

v2_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ 
             # s(Seagrass_Spp,bs="ts",k=4) +
                     # s(Nitrate.Mean,bs="ts",k=4)+
                     s(Dist_To_Shore,bs="ts",k=4) +
                     s(Dist_To_River,bs="ts",k=4) +
                     s(Percent_Silt,bs="ts",k=4) + 
                     s(Depth_m,bs="ts",k=4) +
                                  s(Rhizome_Stock_g_per_sqm,bs="ts",k=4)+

                     as.factor(Factor) +
                     as.factor(HA_PA), data=BlueCarbon_QAQC,method="ML")

summary(v2_OCD)


v3_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ 
             # s(Seagrass_Spp,bs="ts",k=4) +
                     # s(Nitrate.Mean,bs="ts",k=4)+
                     s(Dist_To_Shore,bs="ts",k=4) +
                     s(Dist_To_River,bs="ts",k=4) +
                     s(Percent_Silt,bs="ts",k=4) + 
                                  s(Rhizome_Stock_g_per_sqm,bs="ts",k=4)+

                     # s(Depth_m,bs="ts",k=4) +
                     as.factor(Factor) +
                     as.factor(HA_PA), data=BlueCarbon_QAQC,method="ML")

summary(v3_OCD)

plot.gam(v3_OCD,shade=TRUE,shade.col="darkgreen",scheme=2,trans=exp,all.terms=TRUE)

v4_OCD=gam(Organic_Carbon_Stock_g_per_sqm~ 
             # s(Seagrass_Spp,bs="ts",k=4) +
                     # s(Nitrate.Mean,bs="ts",k=4)+
                     # s(Dist_To_Shore,bs="ts",k=4) +
                     s(Dist_To_River,bs="ts",k=4) +
                     s(Percent_Silt,bs="ts",k=4) +
                     # s(Rhizome_Stock_g_per_sqm,bs="ts",k=4)+

                     # s(Depth_m,bs="ts",k=4) +
                     as.factor(Factor) +
                     as.factor(HA_PA), data=BlueCarbon_QAQC,method="ML")

summary(v4_OCD)

plot.gam(v4_OCD,shade=TRUE,shade.col="darkgreen",shift=coef(v4_OCD)[1],scheme=2,all.terms=TRUE)


gam.check(v5_OCD)


AIC(Seagrass_model_OCD_7,Secchi_model_OCD,Depth_model_OCD,Seagrass_Spp_Cover_model_OCD,Sand_model_OCD,Silt_model_OCD,Sediment_model_OCD,Nitrate_Mean_model_OCD,Treatment_Mean_model_OCD,TH_PA_model_OCD,SPP_PA_model_OCD, v4_OCD)


```



```{r}
# ORGANIC CARBON Stocks

OC_gam_base=mgcv::gam(Organic_Carbon_Stock_g_per_sqm ~ 1,data=BlueCarbon_QAQC,method="ML")

model.set.OC=generate.model.set(use.dat=BlueCarbon_QAQC, 
                                  test.fit=OC_gam_base,
                          pred.vars.cont=cont.preds,
                          # cyclic.vars="month",
                          pred.vars.fact=cat.preds,
                          # null.terms = null.vars,
                          # factor.factor.interactions = TRUE,
                          smooth.smooth.interactions = TRUE,
                          cov.cutoff = 0.50,
                          max.predictors = 5,
                          k=4, bs.arg="'ts'")


out.list.OC=fit.model.set(model.set.OC)


#examine the output
names(out.list.OC)
out.list.OC$failed.models
length(out.list.OC$success.models)
mod.table.OC=out.list.OC$mod.data.out
mod.table.OC=mod.table.OC[order(mod.table.OC$AICc),]
head(mod.table.OC)

OC_ModelTable=mod.table.OC

write.csv(OC_ModelTable,file ="model_output/OC_ModelTable.csv")

```
